### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by MMCMA** [bashtage/arch#108]
When i try to use
     
     pip install git+git://github.com/bashtage/arch.git

The installation fails with the following error message:

`Command "/opt/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-z6aplqe2-build/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-2x3mdls0-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-z6aplqe2-build/`

I use Ubuntu 14.04 with python 3.5.0 (anaconda)

Update:
It seems like I have an issue not only with arch but also with other installtions packages. Most other packages seem to work, so I was initially assuming the problem was arch related, sorry. I will leave the issue for now open (feel free to close it) and asked a [question] (http://stackoverflow.com/questions/35985586/gcloud-problems-with-pip-install)  instead.

**Comment by MMCMA** [comment]
Sovled the problem, gcc was missing on my instance. sorry about that.

**Comment by bashtage** [comment]
Thanks for self helping, and for closing.
