### ISSUE TITLE
GJR-GARCH: how to implement γϵ2t−1I[ϵt−1<0]?

### ISSUE THREAD

**Issue by sleepykid** [bashtage/arch#109]
For regular garch I've got this:
σ2t=ω+αϵ2t−1+βσ2t−1
which is coded as:
res=am.fit(update_freq=5)
σ2t=res.params['omega'] + res.params['alpha[1]']*res.resid**2+res.conditional_volatility**2 *res.params['beta[1]']

however, for GJR-GARCH:
σ2t=ω+αϵ2t−1+γϵ2t−1I[ϵt−1<0]+βσ2t−1
I don't know how to code: γϵ2t−1I[ϵt−1<0]
I'm guessing: 
 γϵ2t−1 = res.params['gamma[1]']*res.resid**2

but not sure how do to:
I[ϵt−1<0]

any help would be appreciated,
thanks

**Comment by bashtage** [comment]
This innovation is `res.resid**2 * (res.resid<0)`
