### ISSUE TITLE
[BUG] Warnings cannot be ignored

### ISSUE THREAD

**Issue by dragonator4** [bashtage/arch#124]
Please refer to this SO question asked by me: http://stackoverflow.com/q/39993792/3765319

Basically, I make thousands of calls to fit a Constant Mean TARCH model, of which a few hundred will fail convergence. I would like a way to ignore warnings raised by the solver, so that the warnings do not slow my Jupyter notebook down. The best solution seems to be to change lines [507-511 in /univariate/base.py](https://github.com/bashtage/arch/blob/master/arch/univariate/base.py#L507) to these:

```
warnings.filterwarnings('always', append=True)
warnings.warn(convergence_warning.format(code=imode,
                                         string_message=smode),
              ConvergenceWarning)
```

This way, it will not override any user-defined warnings filters.

**Comment by bashtage** [comment]
This makes sense - I wanted to make sure the convergence warning would be shown multiple times when working interactively.

As a workaround, you could also capture stdout or stderr when running your code, which would swallow the warnings.

**Comment by bashtage** [comment]
I added a flag to fit that will permit filtering.  Let me know if you have any problems.
