### ISSUE TITLE
Failed convergence

### ISSUE THREAD

**Issue by thrasibule** [bashtage/arch#150]
I'm getting some failed convergence from fmin_slsqp while estimating a Garch(1,1) model on an actual time series.

First I noticed that the log likelihood was being evaluated on negative values for sigma2, 
and I came upon this line which seems a bit suspect:

https://github.com/bashtage/arch/blob/master/arch/univariate/recursions.pyx#L196

To me, it looks like some sort of heuristic to limit the values of sigma2 to some reasonable values. However sigma2[t] could be greater that var_bounds[t,1] but arbitrarily close, so that sigma2[t] could become a negative number, arbitrarily large even. So maybe it would be better to replace that line by max(log(sigma2[t] - var_bounds[t,1]), 0). Although there might be some theoretical reasons for using a log here. Note that similar lines exist for the other type of recursions.

After making that fix, the log_likelihood is only evaluated on positive numbers for sigma2, so there is progress.  However slsqp still fails to converge but that's another issue...

**Comment by bashtage** [comment]
Could you post the data somewhere and the command you are using the fit the model?  If sensitive, you could email me.  The variances should never go negative, and so if they are then there is a mistake.

**Comment by bashtage** [comment]
I think you are right that this should be something that smoothly transitions to the log() bit, but never is negative.

**Comment by thrasibule** [comment]
Data is not sensitive: https://gist.github.com/thrasibule/ac0fe568028a350cf60dfa72f6ab0ba2. These are daily returns for IG (investment grade) index. This is what I'm doing:

```python
import pandas as pd
from arch import arch_model
ig = pd.read_csv("returns.csv", index_col=True )
am = arch_model(ig)
am.fit()
```

**Comment by bashtage** [comment]
It helps to multiply returns by 100.  This avoids the problem of having a very small value for omega in the model.

**Comment by thrasibule** [comment]
Thanks for the tip, it works great! And thanks for the quick fix as well!
