### ISSUE TITLE
Missing imports in __init__.py ?

### ISSUE THREAD

**Issue by LABclimate** [bashtage/arch#164]
Hi,
I just very briefly wanted to report an issue I had after installing the arch package with anaconda:
`conda install -c https://conda.binstar.org/bashtage arch`

Accessing the bootstrapping module with
`from arch.bootstrap import *` 
was impossible unless manually extending `__init__.py` with
`from .bootstrap import *`

Maybe I got something wrong?!
Thanks!

**Comment by bashtage** [comment]
Could you post the output of pandas.show_versions().

**Comment by LABclimate** [comment]
`In [419]: pd.show_versions()`

INSTALLED VERSIONS
------------------
commit: None
python: 2.7.11.final.0
python-bits: 64
OS: Linux
OS-release: 3.19.0-32-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_GB.UTF-8
LOCALE: en_GB.UTF-8

pandas: 0.19.1
nose: 1.3.7
pip: 8.1.1
setuptools: 20.7.0
Cython: 0.25.2
numpy: 1.11.2
scipy: 0.18.1
statsmodels: 0.8.0
xarray: 0.7.2
IPython: 5.1.0
sphinx: None
patsy: 0.4.1
dateutil: 2.5.2
pytz: 2016.3
blosc: None
bottleneck: 1.1.0
tables: None
numexpr: None
matplotlib: 1.5.3
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: None
httplib2: None
apiclient: None
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: 2.8
boto: None
pandas_datareader: None

**Comment by bashtage** [comment]
Thanks for reporting this -- it has now been fixed and will be available through conda/pypi at the next release.
