### ISSUE TITLE
How to get control over the sample size?

### ISSUE THREAD

**Issue by LABclimate** [bashtage/arch#165]
Hello,

I would like to use bootstrap to calculate statistical significance of mean values of composites.
The composites have length `l` and are taken from a time-series of length `L > l`. Now I would like to compute null-composites by randomly selecting the _same number of dates_ (i.e.: `l` elements) from the whole time-series as had been in the original composite.

Playing around I ended up with:
`from arch.bootstrap import MovingBlockBootstrap`
`x = numpy.arange(1000) ` (original dataset)
`MovingBlockBootstrap(3,x).conf_int(numpy.mean, reps=10000, size=.95)`

However, MovingBlockBootstraps leaves me with composites of length `l = L = 1000`. Is there a way to change this?

I wondered, whether a function like 
`import random`
`def func(x): return np.mean(random.sample(x,l))` 
could do the job. But testing this with `l=200,` I got quite high fluctuations for the confidence intervals...

I would be very happy about any hint!
Thank you very much!
L

PS: I'm not sure, whether this github page is the right place to ask that kind of questions. If not I am happily willing to migrate the question to any other forum.

**Comment by bashtage** [comment]
The bootstrap sample is the same size as the original one.  If you want. Smaller sample, you could do something like

```
k=20
def somestat(x):
    return stat(x[:k])
```

This is inefficient but simple.

**Comment by bashtage** [comment]
Let me know if this works for you.
