### ISSUE TITLE
Installation Failure with Conda

### ISSUE THREAD

**Issue by ManchesterWuer** [bashtage/arch#167]
When I was trying to install arch 4.0 by using `conda install -c https://conda.binstar.org/bashtage arch` in Anaconda 4.3.1(Python 3.6 version), I got error showing:

> UnsatisfiableError: The following specifications were found to be in conflict:
> arch 4.0* -> numpy 1.10* -> python 2.7*
> python 3.6*

Why?

**Comment by bashtage** [comment]
There was no build for 3.6 on anaconda.org.  I have released 4.1 which contains some small bug fixes within an hour or so there should be one for 3.6 on anaconda.org.

**Comment by bashtage** [comment]
It has been uploaded so I'm going to close. Let me know if you have any problems.
