### ISSUE TITLE
Logic behind starting_values calcs for GARCH

### ISSUE THREAD

**Issue by xxipei** [bashtage/arch#168]
Hi, Kevin:

Could you please help explain what is the logic behind the starting_values calcs for GARCH? 

The line   target *= (scale ** power) is confusing. It raises up the target by scaling with variable "scale" which is the ratio between the estimated variance and the target variance. The power for scale seems problematic. 

For example, suppose power = 3, then

target = sigma_hat^3 
scale is sigma^2 / sigma_hat^2

And the nextline "target *= (scale ** power)" gives
sigma_hat^3 * ( sigma^6 / sigma_hat^6 ) 

Could you explain? Thank you!

    def starting_values(self, resids):
        p, o, q = self.p, self.o, self.q
        power = self.power
        alphas = [.01, .05, .1, .2]
        gammas = alphas
        abg = [.5, .7, .9, .98]
        abgs = list(itertools.product(*[alphas, gammas, abg]))

        target = np.mean(abs(resids) ** power)
        scale = np.mean(resids ** 2) / (target ** (2.0 / power))
        target *= (scale ** power)

        svs = []
        var_bounds = self.variance_bounds(resids)
        backcast = self.backcast(resids)
        llfs = zeros(len(abgs))
        for i, values in enumerate(abgs):
            alpha, gamma, agb = values
            sv = (1.0 - agb) * target * ones(p + o + q + 1)
            if p > 0:
                sv[1:1 + p] = alpha / p
                agb -= alpha
            if o > 0:
                sv[1 + p:1 + p + o] = gamma / o
                agb -= gamma / 2.0
            if q > 0:
                sv[1 + p + o:1 + p + o + q] = agb / q
            svs.append(sv)
            llfs[i] = self._gaussian_loglikelihood(sv, resids, backcast,
                                                   var_bounds)
        loc = np.argmax(llfs)

        return svs[loc]

**Comment by bashtage** [comment]
This is a simple attempt to address the Jensen's inequality with guessing intercept starting values.  I think it might have been off by a factor of 2 (e.g. power / 2) and I have now updated to reflect this.
