### ISSUE TITLE
extracting residual from garch

### ISSUE THREAD

**Issue by AviralKumarTiwari** [bashtage/arch#170]
can someone tell me how to extract residuals from ARCH/GARH type of models in python in order to perform additional diagnostic tests on it such as LB(20), ARCH test, normality etc. 

For example i am trying

import numpy as np
import pyflux as pf
import pandas as pd
from pandas_datareader import DataReader
from datetime import datetime
import matplotlib.pyplot as plt
%matplotlib inline

jpm = DataReader('JPM',  'yahoo', datetime(2006,1,1), datetime(2016,3,10))
returns = pd.DataFrame(np.diff(np.log(jpm['Adj Close'].values)))
returns.index = jpm.index.values[1:jpm.index.values.shape[0]]
returns.columns = ['JPM Returns']

skewt_model = pf.SEGARCH(p=1, q=1, data=returns, target='JPM Returns')
x = skewt_model.fit()
x.summary()

**Comment by bashtage** [comment]
A fitted model result has an attribute `resid`

**Comment by bashtage** [comment]
You can get the standardized residuals by dividing by `conditional_volatility`

**Comment by bashtage** [comment]
You can see the doc string by typing 

`help(ARCHModelResult)` 

or look here:

http://arch.readthedocs.io/en/latest/univariate/introduction.html#arch.univariate.base.ARCHModelResult
