### ISSUE TITLE
Egarch

### ISSUE THREAD

**Issue by smathaidavis** [bashtage/arch#171]
Hi,

How would I be able to make adjustments using eGarch?  Right now, can only look at smoothing using GJR format.

Thanks.

**Comment by bashtage** [comment]
What are you trying to do?

**Comment by smathaidavis** [comment]
Trying to pull EGarch calculation....not sure how to implement it in the context of the ARCH package (new to python...background is in R).

Right now, pulling GJR Vol using following command:

#GJR Model
garch1=arch_model(returns1,p=1,o=1,q=1)
res=garch1.fit(update_freq=10)
print(res.summary())

How would I go about pulling EGARCH like this?

Thanks...really appreciate your help!

**Comment by bashtage** [comment]
```
arch_model(returns1,p=1,o=1,q=1,vol='EGARCH')
```

**Comment by bashtage** [comment]
Docs here:

http://arch.readthedocs.io/en/latest/univariate/introduction.html#arch.arch_model

**Comment by smathaidavis** [comment]
How would I do the same thing for EWMA (with a lambda of 0.9, etc)?

Thanks for your help!

**Comment by bashtage** [comment]
You have to assemble to mode from parts since there is no direct interface for EWMA.

```
from arch.univariate.mean import ConstantMean
from arch.univariate.volatility import EWMAVariance
mod = ConstantMean(returns, volatility=EWMAVariance())
res = mod.fit()
```
