### ISSUE TITLE
variance definition

### ISSUE THREAD

**Issue by help123456** [bashtage/arch#180]
Hello bashtage,

I am working on a project to forecast volatility from a Garch(p,q) model. 
I have two issues : 
     - what is the difference between forecast.variance function and the res.conditional_volatility? 
       And which one should I use to forecast volatility of the next days (t+1) with the information until t ?
     - which definition do you use for the variance ? (how many days do you use to do the stdev ?)
       I saw that you use the garch fitted function to forecast the volatility step by step but how do you 
       initialize your algorithme (first variance  formula)

Thanks a lot for your work !

**Comment by bashtage** [comment]
Variance is variance - volatility is the sqrt(variance).  In ARCH models, the variance should be forecast and then square rooted.

All variances are for 1 period.  The first period comes from the last fitted value from the in-sample variance series. which comes from estimating the parameters.
