### ISSUE TITLE
Fixed Variance bug in Zig Zag code

### ISSUE THREAD

**Issue by larryguido** [bashtage/arch#189]
Zig-Zag esimtation
A small repetitions of the previous two steps can be used to implement a so-called zig-zag estimation strategy.

Getting an error which is related to the unit_scale variable being set in the compute_variance method within FixedVariance.  -->  'FixedVariance' object has no attribute '_stop'

for i in range(5):
    print(i)
    vol_mod = ZeroMean(res.resid.dropna(), volatility=GARCH(p=1,o=1,q=1))
    vol_res = vol_mod.fit(disp='off')
    variance[22:] = vol_res.conditional_volatility ** 2.0
    fv = FixedVariance(variance )
 # doesn't work -->  fv = FixedVariance(variance, unit_scale=True) #
    mod = HARX(vix, lags=[1,5,22], volatility=fv)
    res = mod.fit(disp='off')
print(res.summary())

File "C:\Users\Larry\Anaconda3\lib\site-packages\arch\univariate\base.py", line 436, in fit
    v.compute_variance(sv_volatility, resids, sigma2, backcast, var_bounds)

  File "C:\Users\Larry\Anaconda3\lib\site-packages\arch\univariate\volatility.py", line 1922, in compute_variance
    if self._stop - self._start != sigma2.shape[0]:

AttributeError: 'FixedVariance' object has no attribute '_stop'

____________________________

?mod
Type:        HARX
String form: HAR(constant: yes, lags: [0:1], [0:5], [0:22], no. of exog: 0, volatility: Fixed Variance (Unit Scale), distribution: Normal distribution)
File:        c:\users\larry\anaconda3\lib\site-packages\arch\univariate\mean.py

**Comment by bashtage** [comment]
Thanks for the report.  I'll try an take a look this week.

**Comment by bashtage** [comment]
@larryguido When I run

```python
for i in range(5):
    print(i)
    vol_mod = ZeroMean(res.resid.dropna(), volatility=GARCH(p=1,o=1,q=1))
    vol_res = vol_mod.fit(disp='off')
    variance[22:] = vol_res.conditional_volatility ** 2.0
    fv = FixedVariance(variance)
    mod = HARX(vix, lags=[1,5,22], volatility=fv)
    res = mod.fit(disp='off')
```

It works as expected.  Similarly when I run the notebook it works as expected.

**Comment by bashtage** [comment]
Closing since this has gone dormant.
