### ISSUE TITLE
IGARCH

### ISSUE THREAD

**Issue by itzybitzy** [bashtage/arch#191]
Is it possible to estimate an IGARCH model? That is, restrict alpha = 1 - beta. I thought perhaps this could be done with `bounds`, but I'm confused about the syntax. 

As an example, I'm trying to replicate Example 2 on page 10 of these slides: http://faculty.chicagobooth.edu/ruey.tsay/teaching/bs41202/sp2017/lec9-17.pdf

**Comment by bashtage** [comment]
I added this using the `EWMAVariance` volatility process in master (not released).  This can be implemented setting `lam=None` when initializing the `EWMAVariance` vol process.

**Comment by bashtage** [comment]
Closing.  Will be out in next release, or use master for now.
