### ISSUE TITLE
HARX: Forecast 1day ahead "Forecasts are not available ... contains exogenous regressors."

### ISSUE THREAD

**Issue by buhbuhtig** [bashtage/arch#198]
Sample code:
`am = arch.univariate.HARX(y=Y,x=X, lags=[1, 2])`
`res = am.fit()`
`res.forecast(horizon=1)`

Error:
> D:\Anaconda3\lib\site-packages\arch\univariate\mean.py 
> ---> 24     res.forecast(horizon=1)
> ...
>        624         if self._x is not None:
> --> 625             raise RuntimeError('Forecasts are not available when the model '
>       626                                'contains exogenous regressors.')
>       627         # Check start
> RuntimeError: Forecasts are not available when the model contains exogenous regressors.

According to docs:

> If model contains exogenous variables (model.x is not None), then only 1-step ahead forecasts are available.

Whats' wrong?
Thx

**Comment by bashtage** [comment]
```
import arch
import numpy as np
Y = np.random.randn(1000,1)
X = np.random.randn(1000,2)
am = arch.univariate.HARX(y=Y,x=X, lags=[1, 2])
res = am.fit()
res.forecast(horizon=1)
```

shows this is definitely a bug.  I'll try and take a look in the next few days.

**Comment by bashtage** [comment]
This is fixed in master and should be out in the next release.
