### ISSUE TITLE
Question about Update_freq for GJR GARCH and EGARCH

### ISSUE THREAD

**Issue by smathaidavis** [bashtage/arch#202]
Hi,

Thank you for maintaining this package.  Question...why is update_freq set to 5 in your example?  Would output materially change if it is simply set to zero?  If I am calculating 30-day conditional volatility, I am still comparing the daily conditional volatilities anyways.  Not sure what frequency set to 5 does until I can set it to  30 and the output for counditional_volatility corresponds to a smooth'd volatility for that period?

Thanks for your help.

**Comment by bashtage** [comment]
This value just controls how frequently you get output.  5 indicates only report every 5th iteration. 1 would report each iteration.  0 turns reporting off.

**Comment by smathaidavis** [comment]
Thanks for getting back to me.  Very much appreciate it.  I think I am a little confused by the use of iteration here (used to doing this calculation in R).  If I have 252 of price data and I want the conditional vol for the 251 days of price change, should I simply leave frequency at zero?  If I want 30 days, should I leave it at 30?  Or am I misunderstanding the role of "iteration" here?

**Comment by smathaidavis** [comment]
Hi,

Apologies for the delay in responding.  I think my confusion is more related to what the iteration input means.  Here is a generic example of how I am trying to use the package:

EGARCHVOL = arch_model(daily_returns, p=1,o=1,q=1, vol='EGARCH')
res = EGARCHVOL.fit(update_freq=5, disp='off')

The vector "daily_returns" is simply 251 days worth of log price change for SPY.  I am trying to calculate the daily conditional volatilities...if I keep iteration=5, will I still get the output for each day or will I be skipping every 5 days.  Or is iterations just refer to the algorithm optimizing itself?  I think I am just confused as to how to read iterations in this case.

Thanks for all your help!

**Comment by bashtage** [comment]
Update freq only affect **displayed** output  while the optimizer is
finding the MLE - it has nothing to do with the model fit.   You will
always get the variances for the full sample.

**Comment by smathaidavis** [comment]
Hi,
Thank you for getting back to me.  Very much appreciate you clearing up my confusion.  I am now following the logic.  Do you have any suggestions as to what number we should use for the number of iterations for 251 observations (days of log price changes) assuming we are looking at an ETF like SPY and a currency like BRL?  Should we set iterations based on whether we think data is highly non-stationary (ie: if extremely non-stationary, make interatios=0).  

Is conditional_volatility output for each individual observation already annualized or is it simply the conditional volatility for that observation?

**Comment by bashtage** [comment]
This parameter is _purely cosmetic_ -- it has no effect on the estimation.  

In this example, note that iterations 3, 5, and 9 are shown when update_freq=3 and that these exactly match the lines labeled 3, 6 and 9 when update_freq=1.
```
import arch
import pandas_datareader as pdr
xlf = pdr.get_data_google('XLF')
r = 100 * xlf.Close.pct_change().dropna()
am = arch.arch_model(r)
```


```
am.fit(update_freq=3)

Iteration:      3,   Func. Count:     24,   Neg. LLF: 3204.466298219404
Iteration:      6,   Func. Count:     46,   Neg. LLF: 3198.4451748100178
Iteration:      9,   Func. Count:     66,   Neg. LLF: 3198.146777809461
```

```
am.fit(update_freq=1)

Iteration:      1,   Func. Count:      6,   Neg. LLF: 3211.539616536533
Iteration:      2,   Func. Count:     16,   Neg. LLF: 3207.5234250330477
Iteration:      3,   Func. Count:     24,   Neg. LLF: 3204.466298219404
Iteration:      4,   Func. Count:     32,   Neg. LLF: 3203.6352208469743
Iteration:      5,   Func. Count:     39,   Neg. LLF: 3198.691022693123
Iteration:      6,   Func. Count:     46,   Neg. LLF: 3198.4451748100178
Iteration:      7,   Func. Count:     53,   Neg. LLF: 3198.3021323197654
Iteration:      8,   Func. Count:     60,   Neg. LLF: 3198.1720515456955
Iteration:      9,   Func. Count:     66,   Neg. LLF: 3198.146777809461
Iteration:     10,   Func. Count:     72,   Neg. LLF: 3198.1413505579176
Iteration:     11,   Func. Count:     78,   Neg. LLF: 3198.141344362736
```

If you want to change the behavior of the optimizer, you need to set `options` using a dictionary which will be directly passed to `scipy.optimize.minimize`. In particular, one key can be `maxiter`.

See http://arch.readthedocs.io/en/latest/univariate/introduction.html#arch.univariate.base.ARCHModelResult.conditional_volatility  

It is not annualized.

**Comment by bashtage** [comment]
Closing since this has gone dormant.
