### ISSUE TITLE
Rolling output

### ISSUE THREAD

**Issue by smathaidavis** [bashtage/arch#204]
Hi,

Is it possible to generate a conditional vol for a frequency of more than one day?  Right now, I am manually coding the following steps:

•	Take Daily Conditional Volatility Output and square all values
•	Sum All squares
•	Divide sum of squares by (total observations – 1) 
•	Take square root of value
•	Multiply by square root of 365 (in this case, there are 365 trading days)

As an example, I do this for time periods of 10-days and 30-days to get a sense of trends in conditional vol.  I am looking to see if it is possible to cut down this process and cut down on the amount of code I am writing.

Thanks for all your help!

**Comment by bashtage** [comment]
I don't think I understand what you are trying to accomplish.  Why would you take the sum of the fitted conditional volatilities?  Perhaps a short code example would be clearer.

**Comment by bashtage** [comment]
Closing since this has gone dormant.

**Comment by smathaidavis** [comment]
Oops...I thought I had actually sent the code.  

This is what I am doing:

`
    df['garch_price_sq_diff'] = df['garch_sm_price_pct_ch']**2
    df['garch_price_sq_diff_rolling'] = df['garch_price_sq_diff'].rolling(GARCH_WINDOW).sum()
    df.dropna(inplace=True)
    df['garch_price_out_rolling_calc'] = np.sqrt(df['garch_price_sq_diff_rolling'] / (GARCH_WINDOW-1)) * np.sqrt(365)
