### ISSUE TITLE
About the GARCH volatility equation

### ISSUE THREAD

**Issue by flcong** [bashtage/arch#207]
Hi, Prof. Sheppard. 

When I was reading the [documentation](http://arch.readthedocs.io/en/latest/univariate/introduction.html), I find that the volatility model used in the program is 
![image](https://user-images.githubusercontent.com/37801658/38386745-b4e71e30-38e3-11e8-87eb-af660352782a.png), 
instead of the common one 
![image](https://user-images.githubusercontent.com/37801658/38386763-c2b7bce0-38e3-11e8-83ca-8e587eafbe6f.png)

Is this a typo in the documentation? Or is the package actually programmed in that way? If so, is there a way to use the second setup in the package?

Thank you very much.

**Comment by bashtage** [comment]
This is a typo.

**Comment by bashtage** [comment]
It is always t-1 on the right-hand side.

**Comment by flcong** [comment]
Thank you very much!

By the way, thanks for your packages in MATLAB and Python. They help a lot.
