### ISSUE TITLE
Egarch results parameters

### ISSUE THREAD

**Issue by bernard199112** [bashtage/arch#214]
Hello,

I have a question regarding the arch model using vol model as EGARCH. 
according to the fomula, the parameters should be alpha, beta, mu, omega and gamma.
however, if you run any data with vol model Egarch, there is no gamma parameter anywhere on the EGARCH results from the arch model package. 

Egarch formula:(Egarch(1,1))
rt=μ+εt
εt=σt*zt
ln(σ2t)=ω+α(|zt−1|−E[|zt−1|])+γzt−1+βln(σ2t−1)

I am not sure if i had missed anything. but would any one please help on this issue?

Thanks!

**Comment by bernard199112** [comment]
Hi, 

thanks for the reply. it resolves my question.

However, i have another question about the Egarch formula, hope you can help me as well: according to the document, the formula of Egarch is the one in the first image. Both of the 'et' after coefficient alpha and gamma is the absolute value. Then no matter the return is positive or negative, the coefficient of the return will be the same, which is equal alpha + gamma. 

From what i read online(the formula in the second image), the 'et' after gamma should not be the absolute number, thus when 'et' is positive, the coefficient will be alpha + gamma, when 'et' is negative, the coefficient will be alpha - gamma. generally, alpha <0 and gamma>0. thus, the asymmetric effect takes place.

so my question is in this package, how is the asymmetric effect works in terms of negative and positive shocks?

Apologies if i miss something obvious here. Thank you very much for your time! 


![image](https://user-images.githubusercontent.com/41590301/44159573-bdde8d00-a0af-11e8-924b-403b4bad3a79.png)

![image](https://user-images.githubusercontent.com/41590301/44159541-aacbbd00-a0af-11e8-81ca-5e34a06869fa.png)

**Comment by bashtage** [comment]
The gamma should not have an absolute value next to it.  The alpha is the symmetric shock and the gamma is the asymmetry term.

**Comment by bernard199112** [comment]
Great.thanks! that is what i understands as well. however, the formula in the first image is what i found on the this package's document and the comment inside the 'mean.py' in this package.
Do you mean this is a typo in the document?

**Comment by bashtage** [comment]
Yes

**Comment by bernard199112** [comment]
Thanks

**Comment by bashtage** [comment]
Closing since this has been resolved.  Thanks for the report.
