### ISSUE TITLE
EGARCH based on non-Normal distributions

### ISSUE THREAD

**Issue by sjvrensburg** [bashtage/arch#221]
The implemented volatility equation for the EGARCH model is specific to the normal distribution. This is despite the fact that the user may specify a non-normal distribution.

### Details
In general, the EGARCH model is specified as:
<a href="https://www.codecogs.com/eqnedit.php?latex=$\ln\sigma_{t}^{2}=\omega&plus;\sum_{i=1}^{p}\left(\left|e_{t-i}\right|-E\left[\left|e_{t-i}\right|\right]\right)&plus;\sum_{j=1}^{o}\gamma\left|e_{t-j}\right|&plus;\sum_{k=1}^{q}\beta_{k}\ln\sigma_{t-k}^{2}$" target="_blank"><img src="https://latex.codecogs.com/gif.latex?$\ln\sigma_{t}^{2}=\omega&plus;\sum_{i=1}^{p}\left(\left|e_{t-i}\right|-E\left[\left|e_{t-i}\right|\right]\right)&plus;\sum_{j=1}^{o}\gamma\left|e_{t-j}\right|&plus;\sum_{k=1}^{q}\beta_{k}\ln\sigma_{t-k}^{2}$" title="$\ln\sigma_{t}^{2}=\omega+\sum_{i=1}^{p}\left(\left|e_{t-i}\right|-E\left[\left|e_{t-i}\right|\right]\right)+\sum_{j=1}^{o}\gamma\left|e_{t-j}\right|+\sum_{k=1}^{q}\beta_{k}\ln\sigma_{t-k}^{2}$" /></a>
for
<a href="https://www.codecogs.com/eqnedit.php?latex=e_{t}=\frac{\epsilon_{t}}{\sigma_{t}}" target="_blank"><img src="https://latex.codecogs.com/gif.latex?e_{t}=\frac{\epsilon_{t}}{\sigma_{t}}" title="e_{t}=\epsilon_{t}/\sigma_{t}." /></a>
In the file `recursions_python.py`, the function `egarch_recursion_python` has <a href="https://www.codecogs.com/eqnedit.php?latex=\inline&space;E\left[\left|e_{t-i}\right|\right]&space;=&space;\sqrt{2/\pi}" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\inline&space;E\left[\left|e_{t-i}\right|\right]&space;=&space;\sqrt{2/\pi}" title="E\left[\left|e_{t-i}\right|\right] = \sqrt{2/\pi}" /></a> hard-coded. This is only the case when the error terms are normally distributed.

For the standardised Student's t distribution, this should be

<a href="https://www.codecogs.com/eqnedit.php?latex=E\left[\left|e_{t-i}\right|\right]=\frac{2\sqrt{\nu-2}\Gamma\left(\left(\nu&plus;1\right)/2\right)}{\sqrt{\pi}\left(\nu-1\right)\Gamma\left(\nu/2\right)}" target="_blank"><img src="https://latex.codecogs.com/gif.latex?E\left[\left|e_{t-i}\right|\right]=\frac{2\sqrt{\nu-2}\Gamma\left(\left(\nu&plus;1\right)/2\right)}{\sqrt{\pi}\left(\nu-1\right)\Gamma\left(\nu/2\right)}" title="E\left[\left|e_{t-i}\right|\right]=\frac{2\sqrt{\nu-2}\Gamma\left(\left(\nu+1\right)/2\right)}{\sqrt{\pi}\left(\nu-1\right)\Gamma\left(\nu/2\right)}" /></a>

and, for the GED, it should be

<a href="https://www.codecogs.com/eqnedit.php?latex=E\left[\left|e_{t-i}\right|\right]=\frac{\Gamma\left(2/\nu\right)}{\sqrt{\Gamma\left(1/\nu\right)\Gamma\left(3/\nu\right)}}." target="_blank"><img src="https://latex.codecogs.com/gif.latex?E\left[\left|e_{t-i}\right|\right]=\frac{\Gamma\left(2/\nu\right)}{\sqrt{\Gamma\left(1/\nu\right)\Gamma\left(3/\nu\right)}}." title="E\left[\left|e_{t-i}\right|\right]=\frac{\Gamma\left(2/\nu\right)}{\sqrt{\Gamma\left(1/\nu\right)\Gamma\left(3/\nu\right)}}." /></a>

### Possible Solution
Implement a method in the distribution class that calculates <a href="https://www.codecogs.com/eqnedit.php?latex=\inline&space;E\left[\left|e_{t-i}\right|\right]" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\inline&space;E\left[\left|e_{t-i}\right|\right]" title="E\left[\left|e_{t-i}\right|\right]" /></a> for the specified distribution and have `egarch_recursion_python` call that method. It can also raise an error if the distribution doesn't implement the method.

I could, if you want me to, try and implement this myself and create a pull request. But I'm somewhat pressured for time right now. Also, I've never done a pull request before.

**Comment by sjvrensburg** [comment]
Thank you, for your quick reply. I didn't quite realise that, but your explanation makes perfect sense. Also, I was trying to modify the code and quickly realised that it's not as simple as imagined. The distribution object doesn't get passed to the volatility recursion (nor should it in most cases). Changing that would require more modifications than I can currently stomach.

**Comment by bashtage** [comment]
What could be helpful would be at add a method to the distributions to
compete this value for a specific distn.  Not essential though.
