### ISSUE TITLE
Add custom scenarios to the forecast method

### ISSUE THREAD

**Issue by gioxc88** [bashtage/arch#225]
Dear Professor Sheppard,
for practical pourposes it would be great to add the option to pass custom scenarios to the forecast method of the arch.univariate.base.ARCHModelResult class.

I took my time to look into the various modules of your package.
The main idea is to change the `rng()` that you call in the volatility._bootstrap_forecast adding an if condition that allows the user to pass the custom scenarios if specified among the function arguments.

Would you consider adding this option In future release?
It would be great for parallel filtered bootstrap.

I really think it would be very easy to add this feature to the package making it more similar to MATLAB counterpart.

Thank you for your attention.
Best Regards

**Comment by bashtage** [comment]
I think this is fairly straightforward but I haven't had time to get around to it.  A pull request that implements this would be welcomed.

I think the only change would be to add a parameter to forecast called `rng` that would be a callable.  This `rng` would be used in place of the default `rng` when producing forecasts by simulation.  The callable `rng` would be responsible for producing the exact shock values required at the right time (e.g. a large shock 10 days in the future).

**Comment by gioxc88** [comment]
thank you very much for the answer.
I really look forward to this implementation!!!

**Comment by bashtage** [comment]
The changes in #227 allow a custom generator to be used for simulation-based forecasting. The can be any callable that return random numbers.   I think this will allow what you are looking for.

**Comment by bashtage** [comment]
This is not in master.  It will be in the next release.

I made a notebook explaining how one could implement custom scenarios:

http://bashtage.github.io/arch/doc/univariate/univariate_volatility_scenarios.html

**Comment by gioxc88** [comment]
Thank you professor, 
now this is my official Matlab replacement for multivariate garch!!!
