### ISSUE TITLE
Trouble in installing arch module

### ISSUE THREAD

**Issue by hanahanamarket** [bashtage/arch#239]
I had tried ti install arch module, but I have been rejected to install.
I use Windows10 and my development environment is JupyterNotebook.
I tried both of "conda install arch" and "!pip install  arch".
I can't specify the cause of this error.

Could you give me a solution?
 
####################     error sentence is bellow   #######################

Collecting arch
  Using cached https://files.pythonhosted.org/packages/80/69/4cab7d2d07e3d592346bcc94023cfc5eb64f93f3aafe906613057ba0a369/arch-4.5.0.tar.gz
Requirement already satisfied: numpy>=1.12 in c:\users\owner\anaconda3\lib\site-packages (from arch) (1.13.3)
Requirement already satisfied: Cython>=0.24 in c:\users\owner\anaconda3\lib\site-packages (from arch) (0.26.1)
Requirement already satisfied: scipy>=0.19 in c:\users\owner\anaconda3\lib\site-packages (from arch) (0.19.1)
Requirement already satisfied: pandas>=0.20 in c:\users\owner\anaconda3\lib\site-packages (from arch) (0.23.4)
Requirement already satisfied: statsmodels>=0.8 in c:\users\owner\anaconda3\lib\site-packages (from arch) (0.8.0)
Requirement already satisfied: pytz>=2011k in c:\users\owner\anaconda3\lib\site-packages (from pandas>=0.20->arch) (2017.2)
Requirement already satisfied: python-dateutil>=2.5.0 in c:\users\owner\anaconda3\lib\site-packages (from pandas>=0.20->arch) (2.6.1)
Requirement already satisfied: six>=1.5 in c:\users\owner\anaconda3\lib\site-packages (from python-dateutil>=2.5.0->pandas>=0.20->arch) (1.11.0)
Building wheels for collected packages: arch
  Running setup.py bdist_wheel for arch: started
  Running setup.py bdist_wheel for arch: finished with status 'error'
  Complete output from command c:\users\owner\anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\owner\\AppData\\Local\\Temp\\pip-install-dzz3n05n\\arch\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d C:\Users\owner\AppData\Local\Temp\pip-wheel-sors7p6b --python-tag cp36:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.6
  creating build\lib.win-amd64-3.6\arch
  copying arch\_version.py -> build\lib.win-amd64-3.6\arch
  copying arch\__init__.py -> build\lib.win-amd64-3.6\arch
  creating build\lib.win-amd64-3.6\arch\bootstrap
  copying arch\bootstrap\base.py -> build\lib.win-amd64-3.6\arch\bootstrap
  copying arch\bootstrap\multiple_comparison.py -> build\lib.win-amd64-3.6\arch\bootstrap
  copying arch\bootstrap\_samplers_python.py -> build\lib.win-amd64-3.6\arch\bootstrap
  copying arch\bootstrap\__init__.py -> build\lib.win-amd64-3.6\arch\bootstrap
  creating build\lib.win-amd64-3.6\arch\compat
  copying arch\compat\numba.py -> build\lib.win-amd64-3.6\arch\compat
  copying arch\compat\pandas.py -> build\lib.win-amd64-3.6\arch\compat
  copying arch\compat\python.py -> build\lib.win-amd64-3.6\arch\compat
  copying arch\compat\__init__.py -> build\lib.win-amd64-3.6\arch\compat
  creating build\lib.win-amd64-3.6\arch\tests
  copying arch\tests\__init__.py -> build\lib.win-amd64-3.6\arch\tests
  creating build\lib.win-amd64-3.6\arch\unitroot
  copying arch\unitroot\unitroot.py -> build\lib.win-amd64-3.6\arch\unitroot
  copying arch\unitroot\__init__.py -> build\lib.win-amd64-3.6\arch\unitroot
  creating build\lib.win-amd64-3.6\arch\univariate
  copying arch\univariate\base.py -> build\lib.win-amd64-3.6\arch\univariate
  copying arch\univariate\distribution.py -> build\lib.win-amd64-3.6\arch\univariate
  copying arch\univariate\mean.py -> build\lib.win-amd64-3.6\arch\univariate
  copying arch\univariate\recursions_python.py -> build\lib.win-amd64-3.6\arch\univariate
  copying arch\univariate\volatility.py -> build\lib.win-amd64-3.6\arch\univariate
  copying arch\univariate\__init__.py -> build\lib.win-amd64-3.6\arch\univariate
  creating build\lib.win-amd64-3.6\arch\utility
  copying arch\utility\array.py -> build\lib.win-amd64-3.6\arch\utility
  copying arch\utility\cov.py -> build\lib.win-amd64-3.6\arch\utility
  copying arch\utility\exceptions.py -> build\lib.win-amd64-3.6\arch\utility
  copying arch\utility\timeseries.py -> build\lib.win-amd64-3.6\arch\utility
  copying arch\utility\__init__.py -> build\lib.win-amd64-3.6\arch\utility
  creating build\lib.win-amd64-3.6\arch\tests\bootstrap
  copying arch\tests\bootstrap\test_bootstrap.py -> build\lib.win-amd64-3.6\arch\tests\bootstrap
  copying arch\tests\bootstrap\test_multiple_comparison.py -> build\lib.win-amd64-3.6\arch\tests\bootstrap
  copying arch\tests\bootstrap\__init__.py -> build\lib.win-amd64-3.6\arch\tests\bootstrap
  creating build\lib.win-amd64-3.6\arch\tests\unitroot
  copying arch\tests\unitroot\test_unitroot.py -> build\lib.win-amd64-3.6\arch\tests\unitroot
  copying arch\tests\unitroot\__init__.py -> build\lib.win-amd64-3.6\arch\tests\unitroot
  creating build\lib.win-amd64-3.6\arch\tests\univariate
  copying arch\tests\univariate\test_distribution.py -> build\lib.win-amd64-3.6\arch\tests\univariate
  copying arch\tests\univariate\test_forecast.py -> build\lib.win-amd64-3.6\arch\tests\univariate
  copying arch\tests\univariate\test_mean.py -> build\lib.win-amd64-3.6\arch\tests\univariate
  copying arch\tests\univariate\test_recursions.py -> build\lib.win-amd64-3.6\arch\tests\univariate
  copying arch\tests\univariate\test_variance_forecasting.py -> build\lib.win-amd64-3.6\arch\tests\univariate
  copying arch\tests\univariate\test_volatility.py -> build\lib.win-amd64-3.6\arch\tests\univariate
  copying arch\tests\univariate\__init__.py -> build\lib.win-amd64-3.6\arch\tests\univariate
  creating build\lib.win-amd64-3.6\arch\tests\utility
  copying arch\tests\utility\test_array.py -> build\lib.win-amd64-3.6\arch\tests\utility
  copying arch\tests\utility\test_cov.py -> build\lib.win-amd64-3.6\arch\tests\utility
  copying arch\tests\utility\test_timeseries.py -> build\lib.win-amd64-3.6\arch\tests\utility
  copying arch\tests\utility\__init__.py -> build\lib.win-amd64-3.6\arch\tests\utility
  creating build\lib.win-amd64-3.6\arch\unitroot\critical_values
  copying arch\unitroot\critical_values\dfgls.py -> build\lib.win-amd64-3.6\arch\unitroot\critical_values
  copying arch\unitroot\critical_values\dickey_fuller.py -> build\lib.win-amd64-3.6\arch\unitroot\critical_values
  copying arch\unitroot\critical_values\kpss.py -> build\lib.win-amd64-3.6\arch\unitroot\critical_values
  copying arch\unitroot\critical_values\__init__.py -> build\lib.win-amd64-3.6\arch\unitroot\critical_values
  running egg_info
  writing arch.egg-info\PKG-INFO
  writing dependency_links to arch.egg-info\dependency_links.txt
  writing requirements to arch.egg-info\requires.txt
  writing top-level names to arch.egg-info\top_level.txt
  reading manifest file 'arch.egg-info\SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  writing manifest file 'arch.egg-info\SOURCES.txt'
  copying arch\bootstrap\_samplers.c -> build\lib.win-amd64-3.6\arch\bootstrap
  copying arch\bootstrap\_samplers.pyx -> build\lib.win-amd64-3.6\arch\bootstrap
  copying arch\univariate\recursions.c -> build\lib.win-amd64-3.6\arch\univariate
  copying arch\univariate\recursions.pyx -> build\lib.win-amd64-3.6\arch\univariate
  UPDATING build\lib.win-amd64-3.6\arch/_version.py
  set build\lib.win-amd64-3.6\arch/_version.py to '4.5.0'
  running build_ext
  building 'arch.univariate.recursions' extension
  error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": http://landinghub.visualstudio.com/visual-cpp-build-tools
  
  ----------------------------------------
  Running setup.py clean for arch
  Complete output from command c:\users\owner\anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\owner\\AppData\\Local\\Temp\\pip-install-dzz3n05n\\arch\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" clean --all:
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help
  
  error: option --all not recognized
  
  ----------------------------------------
Failed to build arch
Installing collected packages: arch
  Running setup.py install for arch: started
    Running setup.py install for arch: finished with status 'error'
    Complete output from command c:\users\owner\anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\owner\\AppData\\Local\\Temp\\pip-install-dzz3n05n\\arch\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\owner\AppData\Local\Temp\pip-record-gfoc4fb_\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    running egg_info
    writing arch.egg-info\PKG-INFO
    writing dependency_links to arch.egg-info\dependency_links.txt
    writing requirements to arch.egg-info\requires.txt
    writing top-level names to arch.egg-info\top_level.txt
    reading manifest file 'arch.egg-info\SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'arch.egg-info\SOURCES.txt'
    UPDATING build\lib.win-amd64-3.6\arch/_version.py
    set build\lib.win-amd64-3.6\arch/_version.py to '4.5.0'
    running build_ext
    building 'arch.univariate.recursions' extension
    error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": http://landinghub.visualstudio.com/visual-cpp-build-tools
    
    ----------------------------------------
  Failed building wheel for arch
  Failed cleaning build dir for arch
Command "c:\users\owner\anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\owner\\AppData\\Local\\Temp\\pip-install-dzz3n05n\\arch\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\owner\AppData\Local\Temp\pip-record-gfoc4fb_\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\owner\AppData\Local\Temp\pip-install-dzz3n05n\arch\

**Comment by bashtage** [comment]
You need to have a c compiler installed to do a straightforward Pip
install. But you have to install it from my channel. The alternative method
uses a special flag. You can find instructions on using this flag on the
github repository for this package. You need to pass the special command
called no binary.

**Comment by bashtage** [comment]
This command works (assumes Cython is installed though, which is a small bug):
```cmd
pip install arch --install-option="--no-binary"
```

**Comment by bashtage** [comment]
@hanahanamarket I have updated the wheels on PyPI and Conda.  I'm going to close.  Please reopen if you are still having issues.
