### ISSUE TITLE
About hedgehog_plot ()

### ISSUE THREAD

**Issue by Ripple-Peng** [bashtage/arch#244]
when I used the res.hedgehog_plot(), it draw the same two figure

**Comment by bashtage** [comment]
If you call it with the same arguments on the same result then this is the expected behavior.

**Comment by bashtage** [comment]
Sorry, I don't understand this comment.  I'm going to close.  Please reopen if you are still experiencing an error.  Ideally, a runnable example would help me understand your issue.
