### ISSUE TITLE
Different estimation and forecasting frequency

### ISSUE THREAD

**Issue by DanielZJInvest** [bashtage/arch#256]
From the basic forecast : 
am = arch_model(data, *args)
res = am.fit()
forecast = res.forecast()

It seems to me that estimation frequency is as same as forecast frequency. Sometimes the computational cost is high.  With daily data, if I only want to estimate every 5 days, but forecast every day with latest obs, how should I set the functions? In other words, I want to hold the estimated parameters unchanged for next 5 days but always forecast one day ahead with updated last obs, which is different from setting forecast horizon to 5 days.

Hope I described my question clearly. Thank you

**Comment by DanielZJInvest** [comment]
Can I use the example of Fixed Window Forecasting?
Assume my data is from '2017-1-1' to '2018-1-10'
res = am.fit(last_obs = '2018-1-1')
forecasts = res.forecast(start = '2018-1-2',horizon=1)
For forecast of '2018-1-4', would it use the obs on '2018-1-3'? Would the forecast do in the recursive way with updated obs?

**Comment by bashtage** [comment]
This will do what you want I think:

```
from arch import arch_model
import pandas as pd
import numpy as np
mod = arch_model(None)
sim = mod.simulate([.1,.1,.1,.8],1000)
r = sim.data.copy()
r.index = pd.date_range('2018-1-1',periods=1000)

all_fcasts = []
for idx in range(900,1000-5,5):
    mod =arch_model(r.iloc[:idx+5])
    res = mod.fit(last_obs=r.index[idx], disp='off')
    fcasts = res.forecast(start=r.index[900], horizon=3)
    out = fcasts.variance.iloc[-5:]  # last 5
    all_fcasts.append(out)

pd.concat(all_fcasts, 0)
```

**Comment by DanielZJInvest** [comment]
Problem solved. very thoughtful. Thank you.

**Comment by DanielZJInvest** [comment]
Problem solved. very thoughtful. Thank you.
