### ISSUE TITLE
If  the residual subjects to a Student’s t distribution, how to know the degree of freedom of the distribution?

### ISSUE THREAD

**Issue by WilesDai** [bashtage/arch#265]
Besides, can the arch_model predicts the quantile of the residual?

**Comment by bashtage** [comment]
The degree of freedom is reported in the estimated parameters, e.g., `res.params`.  It is called `nu`. 

I don't directly provide functions to forecast quantile but these are just (for the 1 step ahead)

`fmean + sqrt(fvar)*q`

where `q` is the time-invariant value of the quantile from the standardized returns.

**Comment by bashtage** [comment]
http://bashtage.github.io/arch/doc/univariate/univariate_volatility_forecasting.html#Value-at-Risk-Forecasting

**Comment by grassriver** [comment]
If I use "scipy.stats.t.fit(res.resid)" to estimate the degree of freedom of the innovations, the result is slightly different from "res.params.nu". Why is there a difference between the two degree of freedoms?

**Comment by bashtage** [comment]
Arch uses a standardized students t not a standard students t. The
standardized students t has the same variance for any value of nu. The
standard students t changes both variance and tail shape when nu changes.

**Comment by grassriver** [comment]
If let e = res.resid/res.conditional_volatility, it seems that e still doesn't follow a standardized students t.  I am still confused which variable the degree of freedom "resid.params.nu" belongs to.

**Comment by bashtage** [comment]
Yes, the standardized residuals follow a std t with nu dof.  The variance
of a std t is always 1.
