### ISSUE TITLE
Spyder can't find Arch Package

### ISSUE THREAD

**Issue by Xenzya93** [bashtage/arch#272]
After installing the arch package in my machine and trying to import it into spyder, it returns a notification saying that there is "no module named arch".
Is this normal? maybe i missed a step in installation
I am running python 3.6 on a windows machine
Spyder version is 3.2.8

Thanks!

**Comment by bashtage** [comment]
If you open an ipython session and try to import arch in the standalone
ipython session, what do you see?

**Comment by bashtage** [comment]
I'm going to close this.  Please reopen if you are still having issues.
