### ISSUE TITLE
Error installing arch ...

### ISSUE THREAD

**Issue by terminsen** [bashtage/arch#284]
Hi - 

I tried to install first via 

pip install arch ... 

I got this error: 

ValueError: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216 from C header, got 192 from PyObject

Then I tried to install via 

pip install arch --install-option="--no-binary" ... which resulted in almost the same error: 

AttributeError: type object 'arch.univariate.recursions.array' has no attribute '__reduce_cython__'

Can you help, pls ?

**Comment by bashtage** [comment]
What command are you running to produce the error?

**Comment by terminsen** [comment]
Yes, sorry I forgot to write that: 

from arch import arch_model

I run the above and I get the error.

**Comment by bashtage** [comment]
Which version of python?

**Comment by bashtage** [comment]
Try

pip install arch --no-binary

**Comment by bashtage** [comment]
If you are compiling locally you might also need to update Cython to be
>=0.28

**Comment by terminsen** [comment]
Thank you for your replies. 
So, I tested all the requirements: 
Python (3.5+)
NumPy (1.13+)
SciPy (0.19+)
Pandas (0.21+)
statsmodels (0.8+)

And also I have Cython installed (via pip) version 0.28.2

So, I should be good. 

I was trying pip install arch --no-binary, but got: 

(base) C:\Users\jet>pip install arch --no-binary

Usage:
  pip install [options] <requirement specifier> [package-index-options] ...
  pip install [options] -r <requirements file> [package-index-options] ...
  pip install [options] [-e] <vcs project url> ...
  pip install [options] [-e] <local project path> ...
  pip install [options] <archive url/path> ...

--no-binary option requires 1 argument

**Comment by bashtage** [comment]
`pip install arch --no-binary arch`

**Comment by bashtage** [comment]
The issue is likely due to an incompatibility between your Numpy and the numpy used it in the wheels (1.16).

You can also so

`pip install git+ssh://git@github.com/bashtage/arch.git@4.8.1`

to skip pypi all together.

**Comment by bashtage** [comment]
@terminsen Did this work for you?

**Comment by terminsen** [comment]
Hi Kevin -

Yes, thank you.

Now it seems to work.

Thank you very much for your help !

Kind regards,
Jesper.

**Comment by bashtage** [comment]
Glad it worked.
