### ISSUE TITLE
Example does not run

### ISSUE THREAD

**Issue by jhordano** [bashtage/arch#285]
I just want to run the example that you provide and it does not work.
When I want to upload the arch_model object

from arch import arch_model

I get the error
AttributeError: type object 'arch.univariate.recursions.array' has no attribute '__reduce_cython__'

**Comment by bashtage** [comment]
What version of Numpy do you have? The binary installers are built for 1.16.

**Comment by jhordano** [comment]
I was using Numpy 1.15 that is the reason that it did not work. I update and it is working. 
Thanks !!

**Comment by bashtage** [comment]
Great.
