### ISSUE TITLE
VarianceRatio implementation issue

### ISSUE THREAD

**Issue by codeterm** [bashtage/arch#286]
There are two possible inconsistencies between the literature and the code in VarianceRatio._compute_statistic

1.
```
        elif not robust:
            self._stat_variance = (2 * (2 * q - 1) * (q - 1)) / (2 * q)
```
according to Lo-MacKinlay, the denominator should be 3 * q, instead of 2 * q

2. 
```
        theta += (1 - k / q) ** 2.0 * delta
````
according to Lo-MacKinlay, it should be
```        
        theta += 4 * (1 - k / q) ** 2.0 * delta
```
instead

**Comment by bashtage** [comment]
Thanks for the report.  Fixed in master.
