### ISSUE TITLE
Acceleration constant in IIDBootstrap

### ISSUE THREAD

**Issue by mikedeltalima** [bashtage/arch#288]
According to "An Introduction to the Bootstrap" (pg. 186, equation 14.15) the constant should be computed using differences from mean of the jackknife samples, but https://github.com/bashtage/arch/blob/master/arch/bootstrap/base.py#L490 calculates the difference from `base` (theta_hat) instead. It was perhaps based on equation 11.3 of the same book?

**Comment by bashtage** [comment]
Thanks. Definitely a bug.

**Comment by bashtage** [comment]
Thanks. Fixed in master, out in the next release.
