### ISSUE TITLE
Specify degrees of fredom of Student t

### ISSUE THREAD

**Issue by gioxc88** [bashtage/arch#289]
Dear Professor Sheppard,
Is it possible to implement something that let's you specify the degrees of freedom of the t distribution and estimate the all the other parameters?

In Matlab for example you can fix the df of t distribution before the estimation take place.

Thank you

**Comment by bashtage** [comment]
There is no feature that permits fixing a subset of parameters.  This said, it would be pretty easy to subclass the students't distribution and to make it a FixedStandardizedStudentsT, then you could do something like

`ConstantMean(y, volatility=GARCH(1,0,1), distribution=FixedStandardizedStudentsT(nu=8))`

It would requrie a bit of python to do this though.

**Comment by gioxc88** [comment]
Thank you very much for the hint, I managed to do it.
I ever some one needs it I will add the code below

`class FixedStudentsT(Distribution):
    """
    Standardized Student's distribution for use with ARCH models
    """

    def __init__(self, nu=3, random_state=None):
        super(StudentsT, self).__init__('Fixed Standardized Student\'s t', 
                                        random_state=random_state)
        if nu <= 2.0:
            raise ValueError('The shape parameter must be larger than 2')
        self.param = nu

    def constraints(self):
        return empty(0), empty(0)

    def bounds(self, resids):
        return tuple([])

    def loglikelihood(self, parameters, resids, sigma2, individual=False):

        nu = self.param
        lls = gammaln((nu + 1) / 2) - gammaln(nu / 2) - log(pi * (nu - 2)) / 2
        lls -= 0.5 * (log(sigma2))
        lls -= ((nu + 1) / 2) * \
               (log(1 + (resids ** 2.0) / (sigma2 * (nu - 2))))

        if individual:
            return lls
        else:
            return sum(lls)

    def starting_values(self, std_resid):
        return empty(0)

    def _simulator(self, size):
        std_dev = sqrt(self.param / (self.param - 2))
        return self._random_state.standard_t(self.param, size=size) / std_dev

    def simulate(self, parameters):
        return self._simulator

    def parameter_names(self):
        return []

    def cdf(self, resids, parameters=None):
        self._check_constraints(parameters)
        nu = self.param
        var = nu / (nu - 2)
        return stats.t(nu, scale=1.0 / sqrt(var)).cdf(resids)

    def ppf(self, pits, parameters=None):
        self._check_constraints(parameters)
        pits = asarray(pits)
        nu = self.param
        var = nu / (nu - 2)
        return stats.t(nu, scale=1.0 / sqrt(var)).ppf(pits)`

**Comment by gioxc88** [comment]
`
class FixedStudentsT(Distribution):
    def __init__(self, nu=3, random_state=None):
        super(StudentsT, self).__init__('Fixed Standardized Student\'s t', 
                                        random_state=random_state)
        if nu <= 2.0:
            raise ValueError('The shape parameter must be larger than 2')
        self.param = nu

    def constraints(self):
        return empty(0), empty(0)

    def bounds(self, resids):
        return tuple([])

    def loglikelihood(self, parameters, resids, sigma2, individual=False):

        nu = self.param
        lls = gammaln((nu + 1) / 2) - gammaln(nu / 2) - log(pi * (nu - 2)) / 2
        lls -= 0.5 * (log(sigma2))
        lls -= ((nu + 1) / 2) * \
               (log(1 + (resids ** 2.0) / (sigma2 * (nu - 2))))

        if individual:
            return lls
        else:
            return sum(lls)

    def starting_values(self, std_resid):
        return empty(0)

    def _simulator(self, size):
        std_dev = sqrt(self.param / (self.param - 2))
        return self._random_state.standard_t(self.param, size=size) / std_dev

    def simulate(self, parameters):
        return self._simulator

    def parameter_names(self):
        return []

    def cdf(self, resids, parameters=None):
        self._check_constraints(parameters)
        nu = self.param
        var = nu / (nu - 2)
        return stats.t(nu, scale=1.0 / sqrt(var)).cdf(resids)

    def ppf(self, pits, parameters=None):
        self._check_constraints(parameters)
        pits = asarray(pits)
        nu = self.param
        var = nu / (nu - 2)
        return stats.t(nu, scale=1.0 / sqrt(var)).ppf(pits)`

**Comment by gioxc88** [comment]
`from arch.univariate import Distribution
from numpy import (asarray, empty, log, pi, sqrt, sum)
from scipy.special import gammaln
import scipy.stats as stats


class FixedStudentsT(Distribution):
    def __init__(self, nu=3, random_state=None):
        super(FixedStudentsT, self).__init__('Fixed Standardized Student\'s t',
                                             random_state=random_state)
        if nu <= 2.0:
            raise ValueError('The shape parameter must be larger than 2')
        self.param = nu

    def constraints(self):
        return empty(0), empty(0)

    def bounds(self, resids):
        return tuple([])

    def loglikelihood(self, parameters, resids, sigma2, individual=False):

        nu = self.param
        lls = gammaln((nu + 1) / 2) - gammaln(nu / 2) - log(pi * (nu - 2)) / 2
        lls -= 0.5 * (log(sigma2))
        lls -= ((nu + 1) / 2) * \
               (log(1 + (resids ** 2.0) / (sigma2 * (nu - 2))))

        if individual:
            return lls
        else:
            return sum(lls)

    def starting_values(self, std_resid):
        return empty(0)

    def _simulator(self, size):
        std_dev = sqrt(self.param / (self.param - 2))
        return self._random_state.standard_t(self.param, size=size) / std_dev

    def simulate(self, parameters):
        return self._simulator

    def parameter_names(self):
        return []

    def cdf(self, resids, parameters=None):
        self._check_constraints(parameters)
        nu = self.param
        var = nu / (nu - 2)
        return stats.t(nu, scale=1.0 / sqrt(var)).cdf(resids)

    def ppf(self, pits, parameters=None):
        self._check_constraints(parameters)
        pits = asarray(pits)
        nu = self.param
        var = nu / (nu - 2)
        return stats.t(nu, scale=1.0 / sqrt(var)).ppf(pits)
    `

**Comment by bashtage** [comment]
That is great thanks. 

Might make fixing distribution parameters an option since it seems pretty straight forward.

**Comment by gioxc88** [comment]
> That is great thanks.
> 
> Might make fixing distribution parameters an option since it seems pretty straight forward.

Yes, I just copy/paste your code making very little changes. I took a bit from the Normal distribution class and the rest from the StudentsT.

Thank you again!!
