### ISSUE TITLE
Can't set random_state for arch_model bootstrap 

### ISSUE THREAD

**Issue by quantvol** [bashtage/arch#290]
It seems a model from arch_model can't accept a random_state when doing a forecast with method='bootstrap'.  The forecast function can take a rng argument for 'simulation', and also VolatilityProcess.forecast can take a random_state.  Is there a way to get deterministic output when doing a bootstrap forecast on a mean model like arch_model?

**Comment by bashtage** [comment]
If you pass a random state when calling forecast with bootstrap, do you not
get a deterministic forecast? Looking at it the code it seems you should.

**Comment by quantvol** [comment]
I'm referring to the forecast() function for the class HARX(ARCHModel) defined in mean.py where there is no random_state argument:
https://github.com/bashtage/arch/blob/3dfd977e6cb714917e28c4c9896e4d1fd5ea9f69/arch/univariate/mean.py#L612
I acknowledge that it can be done for a VolatilityProcess (https://github.com/bashtage/arch/blob/146c4888d2d1be85e0da46f5a0b1e541334286da/arch/univariate/volatility.py#L496), but I'm hoping to include the mean in the bootstrap.
Thank you for your response!

**Comment by bashtage** [comment]
Thanks. I see this issue now.  The PR referenced above will fix this in master, and it will be out in the next release.

**Comment by quantvol** [comment]
Great thanks!
