### ISSUE TITLE
Detecting warnings in ARCHModelResult

### ISSUE THREAD

**Issue by quantvol** [bashtage/arch#292]
I'm getting convergence warnings when fitting some arch models, and would like to programmatically refit them using tricks like rescaling the input.  However, I can't find the warning being passed to the function output as a return value, except for text appended to the end of the summary().  I also tried using the warnings package to treat a ConvergenceWarning like an error (so I can use try except), but I believe this is overridden by code in the fit() function.  Am I missing something? Is there a good way to detect convergence warnings besides parsing the text of the summary() output?
Thanks for your help!

**Comment by bashtage** [comment]
You can use `ARCHModelResult._optim_output` which is a SciPY [OptimizeResult](https://docs.scipy.org/doc/scipy-1.3.0/reference/generated/scipy.optimize.OptimizeResult.html).  It would be good to make this public.

**Comment by quantvol** [comment]
Excellent, thanks!
