### ISSUE TITLE
Computing variance from FIGARCH

### ISSUE THREAD

**Issue by dimcarien** [bashtage/arch#295]
Hi,
I'm using Python 3.7. In order to compute the value at risk, I have to forecast FIGARCH and calculate the daily conditional mean and standard deviation. To do that, I used the package ARCH which contains the FIGARCH model. Please find my code below:

```
import numpy as np
import pandas as pd
import scipy as sp
from scipy.stats import stats,norm
import scipy.stats as stats
df = pd.read_excel ('E:\\Book1.xlsx',sheet_name="Sheet3",header=0)
ret_co1 = df.CO1.pct_change().dropna()
mu_co1 = np.mean(ret_co1)
sigma_co1 = np.std(ret_co1)

from arch.univariate import FIGARCH
mod_4 = FIGARCH(p=1, q=1, power=2.0, truncation=1000)
resid_4 = ret_co1 - mu_co1
residu_4 = resid_4.values
var_4 = np.full((1,4595),sigma_co1)
vari_4 = var_4[0]
bc_4 = mod_4.backcast(resid_4)
bn_4 = mod_4.bounds(resid_4)
para=[1,1]
fig_4 = mod_4.compute_variance(parameters=para, resids=residu_4, sigma2=vari_4, backcast=bc_4, var_bounds=bn_4)
```

ret_co1 are my returns
mu_co1 is my mean
residu_4 is my vector of mean residuals I computed as resids = returns - E(returns)
vari_4 is the vector of conditional variance where I put the same variance on each element of the matrix
para[1,1] is for p=1 and q=1

The message error I got is: "a bytes-like object is required, not 'list'" and came from the File "C:\Users\Dimitry\Anaconda3\lib\site-packages\arch\univariate\volatility.py", line 2519, in compute_variance var_bounds)
Can you help me to fix this error please?

**Comment by bashtage** [comment]
I think you should have somethign like

```
import numpy as np
import pandas as pd
import scipy as sp
from scipy.stats import stats,norm
import scipy.stats as stats
df = pd.read_excel ('E:\\Book1.xlsx',sheet_name="Sheet3",header=0)
ret_co1 = df.CO1.pct_change().dropna()
mu_co1 = np.mean(ret_co1)
sigma_co1 = np.std(ret_co1)

from arch.univariate import FIGARCH, ConstantMean
vol = FIGARCH(p=1, q=1, power=2.0, truncation=1000)
mod = ConstantMean(ret_co1, vol=figarch)
res = mod.fit()
print(res)
```

Or are you not trying to fit the model?

As for your code, `pars = [1,1]` shoudl be `para = np.array([1,1])` and you might also need `residu_4 = np.asarray(resid_4.values)`.

**Comment by dimcarien** [comment]
Hi, thanks for you quick answer. I copied pasted your code but I got an error message

```
from arch.univariate import FIGARCH, ConstantMean
vol = FIGARCH(p=1, q=1, power=2.0, truncation=1000)
mod = ConstantMean(ret_co1, vol=Figarch)
res = mod.fit()
print(res)
Traceback (most recent call last):

  File "<ipython-input-74-6bced47d8ffc>", line 3, in <module>
    mod = ConstantMean(ret_co1, vol=Figarch)

NameError: name 'Figarch' is not defined
```

Can you help me on this point please?
+ I understood why you proposed me "constantmean", it's exactly the model I look for the mean : y_t = \mu + \epsilon_t

**Comment by bashtage** [comment]
Sorry,  should be 

```
from arch.univariate import FIGARCH, ConstantMean
figarch = FIGARCH(p=1, q=1, power=2.0, truncation=1000)
mod = ConstantMean(ret_co1, vol=figarch)
res = mod.fit()
print(res)
```

**Comment by dimcarien** [comment]
It doesn't work either. I tried the syntax below and it worked well
```
from arch import arch_model
mod_4 = arch_model(ret_co1, mean='Constant', vol='Figarch', p=1, q=1)
res_4 = mod_4.fit()
print(res_4)
```

Is it good or not?

**Comment by bashtage** [comment]
That should do the same thing.

**Comment by dimcarien** [comment]
Thank you very much

I'm facing with a new issue. I'm aim at comuting the Value At Risk. Below my script:
```
from arch import arch_model
mod_4 = arch_model(ret, mean='Constant', vol='Figarch', p=1, q=1, dist='Normal')
res_4 = mod_4.fit()
q_4 = mod_4.distribution.ppf([0.05])
forecasts_4 = res_4.forecast()
cond_mean_4 = forecasts_4.mean
cond_var_4 = forecasts_4.variance
value_at_risk_4 = - cond_mean_4.values - np.sqrt(cond_var_4).values * q_4[None, :]
print("value_at_risk_4 =",value_at_risk_4)
```

The console displays:
```
Iteration:      1,   Func. Count:      7,   Neg. LLF: -11934.243530093485
Iteration:      2,   Func. Count:     22,   Neg. LLF: -11934.79652516581
Positive directional derivative for linesearch    (Exit mode 8)
            Current function value: -11934.796521675102
            Iterations: 6
            Function evaluations: 22
            Gradient evaluations: 2
value_at_risk_4 = [[      nan]
 [      nan]
 [      nan]
 ...
 [      nan]
 [      nan]
 [0.0591913]]
C:\Users\Dimitry\Anaconda3\lib\site-packages\arch\univariate\base.py:577: ConvergenceWarning: 
The optimizer returned code 8. The message is:
Positive directional derivative for linesearch
See scipy.optimize.fmin_slsqp for code meaning.

  ConvergenceWarning)
```

I don't know how to interpret my value-at-risk result (for instance, if my portfolio is USD 1,000,000). Can you help me on this point please?

What does the error message mean please? (ConvergenceWarning: The optimizer returned code 8. The message is: Positive directional derivative for linesearch. See scipy.optimize.fmin_slsqp for code meaning.)

Thanks again for your help

**Comment by bashtage** [comment]
It should be in % of AUM when you input returns into the function.  

You should probably scale your returns by 100 to improve the estimation.  This will likely improve the convergence and remove the warning.

**Comment by dimcarien** [comment]
Thank you again, your solution worked
I tried with your 3 other distributions ('studentst', 'skewt', 'ged') but I got error message.

For Studendst and GED distributions, I got:
```
Traceback (most recent call last):

  File "<ipython-input-32-6e43c69e09e3>", line 4, in <module>
    q_4 = mod_4.distribution.ppf([0.05])

  File "C:\Users\Dimitry\Anaconda3\lib\site-packages\arch\univariate\distribution.py", line 413, in ppf
    nu = parameters[0]

TypeError: 'NoneType' object is not subscriptable
```

For Skewt distribution, I got:
```
Traceback (most recent call last):

  File "<ipython-input-33-7a722433de0f>", line 4, in <module>
    q_4 = mod_4.distribution.ppf([0.05])

  File "C:\Users\Dimitry\Anaconda3\lib\site-packages\arch\univariate\distribution.py", line 635, in ppf
    eta, lam = parameters

TypeError: cannot unpack non-iterable NoneType object
```

Can you help me on this last point please?
I checked in your code "distribution.py" all the "def ppf", but I don't understand what I'm supposed to do for this 3 distributions

**Comment by dimcarien** [comment]
Hi bashtage, can you cast an eye on my issue please?

**Comment by bashtage** [comment]
You need to pass the parameters.

```
res = mod.fit()
eta_lam = res.params.iloc[-2:]
eta_lam = res.params[['nu','lambda']]
q_4 = mod.distribution.ppf([0.05],eta_lam)
```

**Comment by bashtage** [comment]
This is probably a bug, or at least a bad design/docstring.  Parameters are required in this function.

**Comment by alejandro-cermeno** [comment]
Dear @bashtage:

Thank you for the time you take to answer the questions. Excuse me, do

```
from arch import arch_model
mod_4 = arch_model (ret_co1, mean = 'Constant', vol = 'Figarch', p = 1, q = 1)
res_4 = mod_4.fit ()
print (res_4)
```

implies by default "power = 2.0, truncation = 1000"?  'power = 2.0' can be added. But if you try to specify 'truncation = 1000' the following message appears:

`  arch_model () got an unexpected keyword argument 'truncation'.
`

In any case how could you specify "truncation" from the High-level command "arch_model"?

Thank you very much for your time in implementing this library that serves all econometricians who use Python.

**Comment by bashtage** [comment]
You cannot. You have to use the power level constructor to get access to this configuration parameter.

**Comment by alejandro-cermeno** [comment]
Thanks for your quick response. Then

`mod_4 = arch_model (ret_co1, mean = 'Constant', vol = 'Figarch', p = 1, q = 1)
`

implies by default "power = 2.0, truncation = 1000"?

**Comment by bashtage** [comment]
Yes.  You can inspect individual properties like

```
mod_4.volatility.truncation
```
