### ISSUE TITLE
Compute model losses to evaluate the performance of the model (MCS)

### ISSUE THREAD

**Issue by dimcarien** [bashtage/arch#300]
Hi bashtage, thanks for reading me
I aim at evaluating the performance of my VaR computed with the GARCH model below. I want to use the Model Confidence Set (or other model you developed arch.bootstrap). I read your "Multiple comparisons" documentation, but I don't understand how I obtain my "model losses" and my "benchmark losses". Can you help me please?

```
from arch import arch_model
mod_1 = arch_model(ret, vol='Garch', p=1, o=0, q=1, dist='Normal')
res_1 = mod_1.fit()
q_1 = mod_1.distribution.ppf([0.05])
forecasts_1 = res_1.forecast()
cond_mean_1 = forecasts_1.mean
cond_var_1 = forecasts_1.variance
value_at_risk_1 = - cond_mean_1.values - np.sqrt(cond_var_1).values * 
q_1[None, :]
print("value_at_risk_1 =",value_at_risk_1)
```

**Comment by bashtage** [comment]
You need to find a loss function for VaR models, e.g., the tick loss function.  Compute this for all of your different models and make an array with shape (t,m) where t is the sample size and m is the number of models.  Then use this in MCS. You can see the example in the documentation.

**Comment by dimcarien** [comment]
It's been 2 days since I tried to display the predicted values from my GARCH model, but it doesn't work.
I tried: forecasts_1.values, forecasts_1.results
I checked in your code any function/method which could give me the predicted values, but I didn't find anything. How can I get the predicted values obtained with my GARCH model forecasted?
Thank you very much

**Comment by bashtage** [comment]
Have you worked though the notebooks in the package?

**Comment by dimcarien** [comment]
> Have you worked though the notebooks in the package?

I didn't modify the package. I just looked for anything which can give me the predicted values, but I didn't find anything

**Comment by bashtage** [comment]
See
https://bashtage.github.io/arch/doc/univariate/univariate_volatility_forecasting.html
and
https://bashtage.github.io/arch/doc/univariate/univariate_volatility_forecasting.html#Value-at-Risk-Forecasting
specifically.

**Comment by dimcarien** [comment]
I read the documentation and I found the following class:
`arch.univariate.base.ARCHModelForecastSimulation(values, residuals, variances, residual_variances)`

And with ".values", I'm supposed to compute the predicted values, right?
But it doesn't work in my code and I don't understand why

Link: [https://bashtage.github.io/arch/doc/univariate/forecasting.html](url)

**Comment by bashtage** [comment]
That is a results class. When you want to forecast, just use res.forecast.  Please follow the example in the documentation -- it shows the exact steps used to forecast. 

If you work though the steps in this notebook https://bashtage.github.io/arch/doc/univariate/univariate_volatility_forecasting.html then you will be able to produce forecasts.

**Comment by dimcarien** [comment]
> That is a results class. When you want to forecast, just use res.forecast. Please follow the example in the documentation -- it shows the exact steps used to forecast.
> 
> If you work though the steps in this notebook https://bashtage.github.io/arch/doc/univariate/univariate_volatility_forecasting.html then you will be able to produce forecasts.

If I try sth like:
```
mu=forecasts.mean.iloc[-3:]
sigma=math.sqrt(forecasts.variance.iloc[-3:])
VaR=mu+sigma*q
```

Can you confirm me I get the predicted values of VaR please?

**Comment by bashtage** [comment]
I really can't provide this level of detail.  The issues here are for software support, e.g., bugs or missing features. It looks right but you should speak to someone locally if you aren't certain about how to forecast VaR. I've tried hard to write good documentation so please consult this as well.  I'm going to close this since there does not appear to be any technical issue here.
