### ISSUE TITLE
Out of sample forecast

### ISSUE THREAD

**Issue by jtankx90** [bashtage/arch#301]
Hi Professor,

Even after reading through the documentations, I am still not 100% confident of my code (to achieve what I would like to do) as the VR (Violation Ratio) are quite low-student-t GJR: 0.6 and normal GJR:0.2. Have I understood something wrongly?

My code:
````

### Read data
rice = pd.read_csv('datav2.csv',index_col='Date')
price.index = pd.to_datetime(price.index,format='%d/%m/%y')
price['EURUSD'] = 100*(np.log(1+price['EURUSD'].pct_change()))


burnin=1000
results=[]
sample= 1500
quantile=0.01

###Estimation & forecast
for i in range(sample-burnin+1):
    am = arch_model(price.dropna()[:burnin+i], vol='Garch', p=1, o=1, q=1, dist='studentst')
    sys.stdout.write('.')
    sys.stdout.flush()
    res = am.fit(last_obs=i + burnin, disp='off')
    temp = res.forecast(horizon=1).variance.iloc[-1:]
    results.append(temp)

forecast = pd.concat(results, 0) 


###t-dof
nu = res.params[-1:]
q = -am.distribution.ppf(quantile,nu)
tvar = np.sqrt((nu-2)/nu)[-1]
VaR= (np.sqrt(forecast['h.1'])*q*tvar)[:-1]

###Violation Ratio
VR = sum(price['EURUSD'][burnin:sample] < -VaR)/(quantile*(sample-burnin))
print(VR)
````

This is what I would like to achieve:
1) given a sample size n, use first T observations as "burn-in" period to first estimate the model.
2) Given the parameters, initialise the volatility calculation with either the sample variance of first T observation or w/(1-a-b) and compute volatility from time 1 to T
3) obtain volatility forecast of T+1.
4) re-estimate the model with T+1 observations , obtain re-estimated parameters, repeat step 2 and 3, to obtain volatility forecast
5) At the end of all the estimation, should have n-T volatility forecasts.

Furthermore, I would like to ask:
1) What does the update frequency in am.fit() does? for e.g if update_freq = 5, does that mean, for a given sample n, if we first estimate using T observation, obtain a T+1 forecast. Instead of re-estimating the mode with T+1 observation and obtaining T+2 forecast , the T+2 forecast is computed using the original parameters. The model will only be re-estimated every 5 days (i.e using T+5 observations?
2) Is the initial variance computed with the w/(1-a-b)?

3) From the documentation(under the bootstrap scenario for filtered historical simulation): "This is effectively a simulation method where the simulated shocks are generated using iid sampling from the history of the demeaned and standardized return data". 
Does that mean, instead of using returns as the shocks to compute volatility, the residuals are used (from i.i.d sampling with replacement) ?

4) why does am.distribution.ppf(0.01,[20])) returns -2.398 ? 
using t.ppf(0.01,20) returns -2.53

Thank you for taking the time.

**Comment by bashtage** [comment]
>     1. What does the update frequency in am.fit() does? for e.g if update_freq = 5, does that mean, for a given sample n,

It is only how frequently the log showin the output of the numerical minimization is printed.  How nothing estimating a model. 


>     2\. Is the initial variance computed with the w/(1-a-b)?

No. It uses a backward EWMA. If you don't like this value, you can set another. 


>     3\. Does that mean, instead of using returns as the shocks to compute volatility, the residuals are used (from i.i.d sampling with replacement) ?

Yes, the devolatilized shocks are sampled iid. 





>     4\. why does am.distribution.ppf(0.01,[20])) returns -2.398 ?
>         using t.ppf(0.01,20) returns -2.53

This is a standardized student's t, not a student's t.

**Comment by jtankx90** [comment]
> ```
>>> No. It uses a backward EWMA. If you don't like this value, you can set another.
How can I implement this? Wasn't able to find anything related in the documentations

**Comment by bashtage** [comment]
You don't have to implement it. It is automatic.  You can find it in the code by looking for backcast. It also gets attached to a model after fit is called.

**Comment by jtankx90** [comment]
Hi professor, with the following code, I am getting the error "User backcast value must be strictly positive". 
````
burnin=250
results=[]
sample= 1000
quantile=0.01
for i in range(sample-burnin+1):
    am = arch_model(price.dropna()[:burnin+i], mean='Zero',vol='Garch', p=1, o=0, q=1, dist='studentst')
    sys.stdout.write('.')
    sys.stdout.flush()
    res = am.fit(last_obs=i + burnin, disp='off',backcast=res.params[0]/(1-sum(res.params[1:3])))
    temp = res.forecast(horizon=1).variance.iloc[-1:]
    results.append(temp)

forecast = pd.concat(results, 0) 
print(forecast)

**Comment by bashtage** [comment]
I suspect your backcast value is negative.  It could happen is alpha+beta is close (slightly above 1). How are you backcasting with `res` when you haven't fitted the model yet?

**Comment by jtankx90** [comment]
yes, some of the betas are >1.  Because I found the backcast option in the fit functionality.. then where should backcasting be?

**Comment by bashtage** [comment]
Why are you providing a backcast? It is handled automatically.

**Comment by bashtage** [comment]
I'm going to close this since I think it has been answered.
