### ISSUE TITLE
Generalized Autoregressive Score (GAS) models

### ISSUE THREAD

**Issue by MBounouar** [bashtage/arch#305]
I just recently discovered the ARCH package. Is there a plan to implement Generalized Autoregressive Score (GAS)  ?
Cheers

**Comment by bashtage** [comment]
While I'm a big fan of GAS models, I don't have any plans to implement any.  I'm happy to take a PR that contains one or more though.

**Comment by MBounouar** [comment]
I would need to familiarize myself with the ARCH package a bit more. I'll see if I have time and success to look into it. Thanks
