### ISSUE TITLE
Error in arch_lm_test (arch/univariate/base) for standardized

### ISSUE THREAD

**Issue by gioxc88** [bashtage/arch#313]
Hello prof. Sheppard I think I spot an error in the function in the title in line 1343, when the optional parameter `standardized=True` is specified 

`if standardized:
            resids = resids / self.conditional_volatility.values`

this throws an error `AttributeError: 'numpy.ndarray' object has no attribute 'values'` because the attribute `self.conditional_volatility` is already a numpy array while the code implies it is a pandas Series.

I hope it can be fixed in the next release.
Many thanks

**Comment by bashtage** [comment]
Thanks.  Definitely a bug.  Simple work-around, for now, is to wrap your data in a Series.

**Comment by gioxc88** [comment]
no problem I changed the code on my machine. 
Thank you
