### ISSUE TITLE
change forecasts object to forecastssimulation object?

### ISSUE THREAD

**Issue by HoyaTrader** [bashtage/arch#316]
Hello Professor, 

I am trying to get a forecasts simulation object where the forecast values become available, but I still get a forecasts object instead, despite specifying method='simulation'.

Am I missing something for getting a ARCHModelForecastSimulation object with forecasted values available?

Additionally, is it possible to call the forecast function on a new dataframe/numpy array of univariate out of sample data for generating 1-step ahead predictions?

Thank you for your assistance.

**Comment by bashtage** [comment]
There is no support for changing the dataset after the model has been created.  I think if you need real-time you will need to generate the forecasts outside of the package.  If you are using a basic model like GARCH, then forecast generation is pretty easy. 

The `ARCHModelForecastSimulation` object should be available off the `ARCHModelForecast` object.  The `ARCHModelForecast` object contains the actual (simulation-based) forecasts which are computed from the paths that are retained in `ARCHModelForecastSimulation`.

**Comment by HoyaTrader** [comment]
Thank you very much for your helpful response, Professor!

For generating the forecasts manually - should I use the model summary output, grab the parameter values from the fit, and then plug into the GARCH equations (attached)?
![GARCH_Equations](https://user-images.githubusercontent.com/56007314/65982984-887b3700-e44a-11e9-9b94-10c255fcd5fe.png)

Some clarification on how to properly generate these forecasts would be great, since this is my first in-depth GARCH project.  I take it that I need to first draw from a standard normal random variable, then feed that into epsilon, which then feeds into the variance, and finally the yhat predictions?  Is this the right idea?  I am a bit worried about my model summary output (attached), since I was getting some convergence warnings.
<img width="548" alt="ModelSummary" src="https://user-images.githubusercontent.com/56007314/65983591-da708c80-e44b-11e9-83e6-b2ee610a4a56.PNG">

Lastly, I am not sure what I am missing in getting the actual simulation-based forecasts (forecast.values) for a one-step ahead prediction.  Am I missing something with my code below?  This is more for my curiosity though, since I will need to manually produce the forecasts anyways, to use on new data.

#Model summary
print(model_fit.summary)

plot = model_fit.plot()

# forecast the test set
forecasts = model_fit.forecast(method='simulation')
print(forecasts.values) #this doesn't work

#these work though
print(forecasts.variance.tail())
print(forecasts.mean.iloc[-3:])
print(forecasts.residual_variance.iloc[-3:])
print(forecasts.variance.iloc[-3:])

#this doesn't work
forecasts2 = model_fit.forecast(method='bootstrap')
print(forecasts2.values)

Thank you very much for your assistance!

**Comment by HoyaTrader** [comment]
Would closed form analytical forecasts be possible without simulating draws from random variables?

**Comment by bashtage** [comment]
Which model are you using?  Are you producing 1-step ahead or multiple steps?

**Comment by bashtage** [comment]
If you are using a GARCH model like you have above then you can produce analytical forecasts.

**Comment by HoyaTrader** [comment]
Yes, I am looking to start with a GARCH(1,1) to keep things basic - I am sorry if this is getting very elementary, but which formula would provide the analytical 1-step ahead forecast?  Looking at the GARCH equations, I didn’t realize that simulating draws from a random variable could be avoided when making a 1-step ahead forecast.

Thank you for all your assistance Professor!

**Comment by bashtage** [comment]
The updating formula for a GARCH(1,1) is in the equation you posted above.  The 1-step OOS forecast is

sigma2_oos = omega + alpha * eps[-1]**2 + beta * sigma2[-1]

If you are only asking for 1 step, then using 'simulation' doesn't actually do an simulation since arch is smart enough to only use simulation when required.

**Comment by HoyaTrader** [comment]
Thank you so much for your assistance, Professor :)

This has been a great learning experience for me, and this is all making much more sense now.

Cheers!
