### ISSUE TITLE
A Problem   

### ISSUE THREAD

**Issue by Nipper-TT** [bashtage/arch#317]
AttributeError: type object 'arch.univariate.recursions.array' has no attribute '__reduce_cython__'

**Comment by bashtage** [comment]
Can you post an example showing how this error is produced?  I don't think this is directly caused by Arch.  Also, the full traceback is helpful.

**Comment by bashtage** [comment]
xref cython/cython#1953

**Comment by bashtage** [comment]
What versions are you using?

**Comment by Nipper-TT** [comment]
![image](https://user-images.githubusercontent.com/56535719/66737085-99da2f80-ee9d-11e9-9707-c8fa227f306d.png)
![image](https://user-images.githubusercontent.com/56535719/66737148-c2622980-ee9d-11e9-87a9-78fd2ba6b3f3.png)
python3.7
Thanks.

**Comment by bashtage** [comment]
What version of arch you using, and how did you get it?  Asking because I can't locally produce this?

Are you running this in Spyder?

**Comment by Nipper-TT** [comment]
YES







------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Kevin Sheppard"<notifications@github.com&gt;;
发送时间:&nbsp;2019年10月14日(星期一) 下午4:36
收件人:&nbsp;"bashtage/arch"<arch@noreply.github.com&gt;;
抄送:&nbsp;"T^_^T"<1534001254@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [bashtage/arch] A Problem    (#317)




What version of arch you using, and how did you get it?  Asking because I can't locally produce this?
 
Are you running this in Spyder?

**Comment by Nipper-TT** [comment]
![image](https://user-images.githubusercontent.com/56535719/66738599-7913d900-eea1-11e9-91f2-8200e16ddb4d.png)
I use this

**Comment by bashtage** [comment]
I think this is a bug in Spyder related to module reloading which is not supported.  What happens if you run your code outside of Spyder?

**Comment by Nipper-TT** [comment]
I feel so sad.  my colleague‘ s python pycharm  is ok 
![image](https://user-images.githubusercontent.com/56535719/66739036-6f3ea580-eea2-11e9-9eb4-100dce8e06d7.png)
I will use pycharm try again.

**Comment by bashtage** [comment]
Are you running Python 2 or 3?

**Comment by bashtage** [comment]
I think I have fixed this in master and teh just released 4.10.  You should be able to install 4.10 in Python 3.7 in the next hour or so.

Please let me know if this doesn't fix Spyder.

**Comment by Nipper-TT** [comment]
I updated some&nbsp;site-packages and then use new&nbsp; arch 4.10 . The problem was solved. I can use arch to solve my math problem .


Thanks&nbsp;







------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Kevin Sheppard"<notifications@github.com&gt;;
发送时间:&nbsp;2019年10月14日(星期一) 下午5:15
收件人:&nbsp;"bashtage/arch"<arch@noreply.github.com&gt;;
抄送:&nbsp;"T^_^T"<1534001254@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [bashtage/arch] A Problem    (#317)




Are you running Python 2 or 3?
