### ISSUE TITLE
Hi, I am new to this, correct me if I m wrong.  Why the omega coefficient in GARCH and TARCH(power = 1) estimations are approximately the same. Should not I get square root of GARCH`s omega as omega for TARCH model? 

### ISSUE THREAD

**Issue by ErikVaR** [bashtage/arch#321]
Hi, I am new to this, correct me if I m wrong. Why the omega coefficient in GARCH and TARCH(power = 1) estimations are approximately the same. Should not I get square root of GARCH`s omega as omega for TARCH model? 6 minutes ago

**Comment by bashtage** [comment]
They should have some differences in magnitude, but if the variance of your series is near 1, then they will appear to be the same.

**Comment by ErikVaR** [comment]
Ok, but what about the example in:
https://arch.readthedocs.io/en/latest/univariate/univariate_volatility_modeling.html#

**Comment by bashtage** [comment]
The parameters of the GARCH(1,1) suggest the variance is close to 1.

Long-run variance =   0.0175  / (1-0.1022  -0.8852 ) = 1.388

**Comment by ErikVaR** [comment]
I see, thanks a lot
