### ISSUE TITLE
Overflow when GARCH runs on constant timeseries

### ISSUE THREAD

**Issue by idansc** [bashtage/arch#331]
hi, i'm fitting an arch model to a constant timeseries, and getting the following error:

`OverflowError                             Traceback (most recent call last)
<ipython-input-25-a0e793f6305e> in <module>
----> 1 model_fit = model.fit()

~/anaconda3/lib/python3.7/site-packages/arch/univariate/base.py in fit(self, update_freq, disp, starting_values, cov_type, show_warning, first_obs, last_obs, tol, options, backcast)
    500 
    501         resids = self.resids(self.starting_values())
--> 502         self._check_scale(resids)
    503         if self.scale != 1.0:
    504             # Scale changed, rescale data and reset model

~/anaconda3/lib/python3.7/site-packages/arch/univariate/base.py in _check_scale(self, resids)
    253             else:
    254                 rescale /= 10
--> 255             scale = orig_scale * rescale ** 2
    256         if rescale == 1.0:
    257             return

OverflowError: (34, 'Result too large')`

**Comment by bashtage** [comment]
Likelihood isn't well defined when variance is 0. Should raise a more meaningful error.
