### ISSUE TITLE
TestMeanModel::test_convergence_warning fails when using scipy 1.4.1

### ISSUE THREAD

**Issue by arnoldfarkas** [bashtage/arch#337]
Test case arch/tests/univariate/test_mean.py::TestMeanModel::test_convergence_warning fails when scipy 1.4.1 is used. 

Scipy 1.4.0 was a major releasem, impacted scipy.optimize as well, which can cause this particular test case to fail: there is no convergence warning raised, the scipy.optimize.minimize succeeds.

**Comment by bashtage** [comment]
Fixed in master.
