### ISSUE TITLE
Question about EWMAVariance forecast

### ISSUE THREAD

**Issue by grassriver** [bashtage/arch#344]
Hi, 

I see that arch package provides an EWMA volatility model. 

_http://bashtage.github.io/arch/doc/univariate/generated/arch.univariate.EWMAVariance.html#arch.univariate.EWMAVariance_

The above page gives a brief introduction to this method. But I still don't know how to apply it. For example, I have a series of stock returns, y and lambda is set to 0.94.

`from arch.univariate import EWMAVariance`
`rm = EWMAVariance(0.94)`

How do I get the 1-day volatility forecast using the EWMA volatility model after the above two lines of codes? Could you give us an example?

Thanks!

**Comment by bashtage** [comment]
You need a full model with EWMAVariance as the volatility process.  See the examples in the docs which cover building a model from components.
