### ISSUE TITLE
NAN for ADF test 

### ISSUE THREAD

**Issue by karasjoh000** [bashtage/arch#355]
ran a test on a data that has no Nans and maybe some zero's, and got nan for results

```shell
   Augmented Dickey-Fuller Results   
=====================================
Test Statistic                    nan
P-value                           nan
Lags                                0
-------------------------------------

Trend: Constant
Critical Values: -3.43 (1%), -2.86 (5%), -2.57 (10%)
Null Hypothesis: The process contains a unit root.
Alternative Hypothesis: The process is weakly stationary.
```

**Comment by bashtage** [comment]
Can you share enough of the data to reproduce the issue?

**Comment by bashtage** [comment]
Any help with a time series to reproduce?  I suspect the variance is 0, which is the cause of the nan. Are there a log of 0s?

**Comment by bashtage** [comment]
Going to close since I can't fix what cannot be reproduced. I suspect that the residual variance in your ADF regression is 0 which leads to a nan.
