### ISSUE TITLE
install fails with no-binary

### ISSUE THREAD

**Issue by Chrigoo** [bashtage/arch#361]
Hi Kevin

Using anaconda I have numba 0.45.1 and Cython 0.29.13 (pypi) installed. I followed your advice and tried:

  pip install git+https://github.com/bashtage/arch.git --install-option="--no-binary" --no-build-isolation

Below is the error I get, it seems it tries to uninstall Cython 0.29.13 and install another version where it then fails at "Running setup.py install for cython" ("Unable to find pgen").

Do you have any recommendation how to fix that?

Many thanks and best regards
Christoph

C:\Anaconda\lib\site-packages\pip\_internal\commands\install.py:243: UserWarning: Disabling all use of wheels due to the use of --build-options / --global-options / --install-options.
  cmdoptions.check_install_build_global(options)
Collecting git+https://github.com/bashtage/arch.git
  Cloning https://github.com/bashtage/arch.git to c:\users\christ~1\appdata\local\temp\pip-req-build-tiaqj6fk
  Running command git clone -q https://github.com/bashtage/arch.git 'C:\Users\CHRIST~1\AppData\Local\Temp\pip-req-build-tiaqj6fk'
    Preparing wheel metadata ... done
Requirement already satisfied: property-cached>=1.6.3 in c:\anaconda\lib\site-packages (from arch==4.13+19.g59dbaff5) (1.6.4)
Requirement already satisfied: numpy>=1.14 in c:\anaconda\lib\site-packages (from arch==4.13+19.g59dbaff5) (1.16.5)
Requirement already satisfied: pandas>=0.23 in c:\anaconda\lib\site-packages (from arch==4.13+19.g59dbaff5) (0.25.1)
Requirement already satisfied: statsmodels>=0.9 in c:\anaconda\lib\site-packages (from arch==4.13+19.g59dbaff5) (0.10.1)
Requirement already satisfied: scipy>=1.0.1 in c:\anaconda\lib\site-packages (from arch==4.13+19.g59dbaff5) (1.3.1)
Collecting cython>=0.29.14 (from arch==4.13+19.g59dbaff5)
  Using cached https://files.pythonhosted.org/packages/49/8a/6a4135469372da2e3d9f88f71c6d00d8a07ef65f121eeca0c7ae21697219/Cython-0.29.16.tar.gz
Requirement already satisfied: python-dateutil>=2.6.1 in c:\anaconda\lib\site-packages (from pandas>=0.23->arch==4.13+19.g59dbaff5) (2.8.0)
Requirement already satisfied: pytz>=2017.2 in c:\anaconda\lib\site-packages (from pandas>=0.23->arch==4.13+19.g59dbaff5) (2019.3)
Requirement already satisfied: patsy>=0.4.0 in c:\anaconda\lib\site-packages (from statsmodels>=0.9->arch==4.13+19.g59dbaff5) (0.5.1)
Requirement already satisfied: six>=1.5 in c:\anaconda\lib\site-packages (from python-dateutil>=2.6.1->pandas>=0.23->arch==4.13+19.g59dbaff5) (1.12.0)
Skipping bdist_wheel for arch, due to binaries being disabled for it.
Skipping bdist_wheel for cython, due to binaries being disabled for it.
Installing collected packages: cython, arch
  Found existing installation: cython 0.29.13
    Uninstalling cython-0.29.13:
      Successfully uninstalled cython-0.29.13
  Running setup.py install for cython ... error
    ERROR: Command errored out with exit status 1:
     command: 'C:\Anaconda\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\CHRIST~1\\AppData\\Local\\Temp\\pip-install-7x12nwbk\\cython\\setup.py'"'"'; __file__='"'"'C:\\Users\\CHRIST~1\\AppData\\Local\\Temp\\pip-install-7x12nwbk\\cython\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\CHRIST~1\AppData\Local\Temp\pip-record-m89brese\install-record.txt' --single-version-externally-managed --compile --no-binary
         cwd: C:\Users\CHRIST~1\AppData\Local\Temp\pip-install-7x12nwbk\cython\
    Complete output (7 lines):
    Unable to find pgen, not compiling formal grammar.
    usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
       or: setup.py --help [cmd1 cmd2 ...]
       or: setup.py --help-commands
       or: setup.py cmd --help

    error: option --no-binary not recognized
    ----------------------------------------
  Rolling back uninstall of cython
  Moving to c:\anaconda\lib\site-packages\__pycache__\cython.cpython-37.pyc
   from C:\Users\CHRIST~1\AppData\Local\Temp\pip-uninstall-h75ntylj\cython.cpython-37.pyc
  Moving to c:\anaconda\lib\site-packages\cython-0.29.13.dist-info\
   from c:\anaconda\lib\site-packages\~ython-0.29.13.dist-info
  Moving to c:\anaconda\lib\site-packages\cython.py
   from C:\Users\CHRIST~1\AppData\Local\Temp\pip-uninstall-byv_1jot\cython.py
  Moving to c:\anaconda\lib\site-packages\cython\
   from c:\anaconda\lib\site-packages\~ython
  Moving to c:\anaconda\lib\site-packages\pyximport\
   from c:\anaconda\lib\site-packages\~yximport
  Moving to c:\anaconda\scripts\cygdb-script.py
   from C:\Users\CHRIST~1\AppData\Local\Temp\pip-uninstall-fx8nopge\cygdb-script.py
  Moving to c:\anaconda\scripts\cygdb.exe
   from C:\Users\CHRIST~1\AppData\Local\Temp\pip-uninstall-fx8nopge\cygdb.exe
  Moving to c:\anaconda\scripts\cython-script.py
   from C:\Users\CHRIST~1\AppData\Local\Temp\pip-uninstall-fx8nopge\cython-script.py
  Moving to c:\anaconda\scripts\cython.exe
   from C:\Users\CHRIST~1\AppData\Local\Temp\pip-uninstall-fx8nopge\cython.exe
  Moving to c:\anaconda\scripts\cythonize-script.py
   from C:\Users\CHRIST~1\AppData\Local\Temp\pip-uninstall-fx8nopge\cythonize-script.py
  Moving to c:\anaconda\scripts\cythonize.exe
   from C:\Users\CHRIST~1\AppData\Local\Temp\pip-uninstall-fx8nopge\cythonize.exe
ERROR: Command errored out with exit status 1: 'C:\Anaconda\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\CHRIST~1\\AppData\\Local\\Temp\\pip-install-7x12nwbk\\cython\\setup.py'"'"'; __file__='"'"'C:\\Users\\CHRIST~1\\AppData\\Local\\Temp\\pip-install-7x12nwbk\\cython\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\CHRIST~1\AppData\Local\Temp\pip-record-m89brese\install-record.txt' --single-version-externally-managed --compile --no-binary Check the logs for full command output.

**Comment by bashtage** [comment]
I would first manually upgrade to Cython 0.29.14+ which is required.  Then
you should be able to run the command.

Just do conda update cython which should get you a higher version, and the
pip command you have above should work  I will probably have anew version
in the next couple of weeks.

Best,
Kevin

**Comment by Chrigoo** [comment]
Thanks much Kevin. This fixed it. Details: conda list showed cython was installed with pip, so I run
```pip uninstall cython```

then
  ```conda install cython```
  ```conda list```
shows: name, version, build, channel
cython                    0.29.16          py37h63f7a3c_0    conda-forge

then run again:
pip install git+https://github.com/bashtage/arch.git --install-option="--no-binary" --no-build-isolation

Now this works:
  ```from arch.bootstrap import optimal_block_length```

**Comment by bashtage** [comment]
Closing since fixed.
