### ISSUE TITLE
In GARCH(1,1) is it possible to have alpha+beta>1 ?

### ISSUE THREAD

**Issue by cantaro86** [bashtage/arch#362]
I fitted the GARCH(1,1) model, and I got alpha+beta>1.
I used a quite big dataset (size of ~6000 data points). I also tried to reduce the size and the problem disappeared. 
Is it normal? Or is it a bug? 
Thanks

**Comment by bashtage** [comment]
The parameters are constrained to sum to < 1 by a constrained optimizer, but it allows the values to get slightly outside of 1.  This is usually the sign of misspecified model. What values are you seeing? Is the optimizer converging?

**Comment by cantaro86** [comment]
Thanks a lot for the answer. 
This is the output of the optimizer:

> Iteration:     11,   Func. Count:     80,   Neg. LLF: 31381.772926719816
Iteration:     12,   Func. Count:     89,   Neg. LLF: 31381.77279709752
Optimization terminated successfully.    (Exit mode 0)
            Current function value: 31381.772813609507
            Iterations: 13
            Function evaluations: 100
            Gradient evaluations: 12

The data I used comes from a Monte Carlo simulation of a stochastic volatility model.
I used the following code to initialize the GARCH model (p=q=1 is the choice that minimizes AIC) :

> am = arch_model( train_data, mean='Constant', vol='GARCH', p=1, q=1 )

The summary of the output is:
>          | coef     | std err       | t           | P>\|t\| 
mu       | 0.1640 | 6.232e-02 | 2.631   | 8.507e-03
omega | 0.0533 | 2.313e-02 | 2.306   | 2.112e-02 | 
alpha   | 0.0407 | 3.774e-03 | 10.796 | 3.615e-27 | 
beta     | 0.9593 | 3.706e-03 | 258.815 | 0.000 | 

The sum is:
> res.params[3] + res.params[2] 
> 1.0000007235771817

I want to estimate the long term volatility VL by computing VL = omega / (1-alpha-beta). 
The problem is that I obtain a negative value.
Thanks for the help.

**Comment by bashtage** [comment]
That is on the boundary of the space from a numerical point of view and so everything is working correctly.  

These parameters suggest your model is misspecified.  There probably has been a structural-break -like change in the level of volatility. When you use subsamples you avoid this structural break and so alpha+beta < 1.

When alpha+beta=1 then the LR volatility is not defined, even though alpha and beta can be consistently estimated.
