### ISSUE TITLE
Add forecasting code

### ISSUE THREAD

**Issue by bashtage** [bashtage/arch#38]
The forecasting paths are simple stubs and haven't been implemented.

**Comment by bashtage** [comment]
Mean forecasting in #49

**Comment by gururise** [comment]
Is the forecasting working? 

No matter what I try, I get the same values for the forecasts:
cm = ConstantMean(returns)
res = cm.fit()
res.forecast(horizon=3)

Produces the following:
	h.1	h.2	h.3
Date			
2004-01-05	0.036389	0.036389	0.036389
2004-01-06	0.036389	0.036389	0.036389
2004-01-07	0.036389	0.036389	0.036389
2004-01-08	0.036389	0.036389	0.036389
2004-01-09	0.036389	0.036389	0.036389
2004-01-12	0.036389	0.036389	0.036389

**Comment by bashtage** [comment]
Something seems to be not working as expected.

**Comment by bashtage** [comment]
This is because you have constant means and are looking at the mean forecast.  Volatility forecasting is TBD.

**Comment by icetortoise** [comment]
Not sure if this is the right place to ask..but since volatility forecast is not implemented yet:

How would it be implemented if we want a volatility forecast for next N days? 

I tried to google, and found some mentioned using T+1 forecast and then based on that forecast T+2. I get how we can get T+1 volatility...but how should i get T+1 resid, which is required for T+2 forecast?

Apologies in advance if this is not the right place to ask.

**Comment by heyanyun** [comment]
Volatility forecasting is TBD. how set? plesae show a example.

**Comment by Vincent-Chin** [comment]
It sounds like you'll have to do it manually:
http://quant.stackexchange.com/questions/16730/correctly-applying-garch-in-python

**Comment by Vincent-Chin** [comment]
I've written some code to do the forecast, given an ArchModelResult.  It does execute and return data successfully, though I haven't verified if it produces the same forecasts as an equivalent R function.  Posted below, so anyone else can check for errors/merge it into the code base.

	# this method manually forecasts the arch-family of models, since
	# it is not yet implemented in bashtage/arch
	def garch_forecast(archmodelresult, horizon=1):
		
		import re
		
		model_params = archmodelresult.params
		resid2 = archmodelresult.resid ** 2
		convol2 = archmodelresult.conditional_volatility ** 2
		   
		# first generate the derived datasets    
		factors = pd.DataFrame(index=convol2.index)
		forecasts = pd.DataFrame(index=convol2.index)
		
		for key in model_params.keys():    
			# get the offset (for alpha and beta)
			offset = re.findall(r'\d+', key)
			if len(offset) == 1:
				offset = int(offset[0]) - 1
			else:
				offset = 0

			# generate a value column for this key into the response
			if 'mu' in key:
				pass
			if 'omega' in key:
				pass
			if 'alpha' in key:
				factors[key] = (resid2).shift(offset) * model_params[key]
			if 'beta' in key:
				factors[key] = (convol2).shift(offset) * model_params[key]
		
		# note: these forecasts are aligned such that the forecast is for the
		# 'next' row of returns data.
		#
		# horizons past 1 are defined as:
		# foVariance[n] = omega + sum(alphas + betas) * foVariance[n - 1]
		for h in range(1, horizon + 1):
			colName = 'foVar[' + str(h) + ']'
			
			if h == 1:
				forecasts[colName] = model_params['omega'] + np.sum(factors, axis=1)
			else:
				prevName = 'foVar[' + str(h - 1) + ']'
				forecasts[colName] = model_params['omega'] + (
					np.sum(factors, axis=1) * forecasts[prevName])

		# sums are invalid when anything is nan
		nonValues = np.isnan(factors).any(axis=1)
		for idx in nonValues[nonValues == True].index:
			forecasts.ix[idx,] = np.nan
		
		# return the conditional volatility, not conditional variance
		forecasts = np.sqrt(forecasts)
		return forecasts

**Comment by Vincent-Chin** [comment]
Dataset: https://dl.dropboxusercontent.com/u/9232427/resids.csv

![pred_result](https://cloud.githubusercontent.com/assets/1965911/10401601/ebe583a4-6e8d-11e5-8af6-36c9c00e9b80.png)

**Comment by heyanyun** [comment]
i think garch forecast  is bad,all the forecast result  are 
negative or positive. real date  like this 0.2 0.6 -0.2 0.3 -0.5
but forecast  date  like this 0.2 0.6 0.2 0.3 0.5

**Comment by Vincent-Chin** [comment]
@heyanyun The GARCH models variance, which is a range +/- around a central point.  A value of 0.2 is the same as [-0.2, +0.2].  -0.2 would be [+0.2, -0.2].  It's the same thing.

**Comment by bashtage** [comment]
@heyanyun Do you mean date or data?

**Comment by heyanyun** [comment]
sorry ，all the forecast data result are 
negative or positive,
i thin forecast data result like this 0.2 0.6 -0.2 0.3 -0.5 is good
but garch forecast like this 0.2 0.6 0.2 0.3 0.5 or -0.2 -0.6 -0.2 -0.3 -0.5

**Comment by bashtage** [comment]
Forecasts are in the #132

**Comment by bashtage** [comment]
Closed by #132
