### ISSUE TITLE
Pandas '1.0.3' ImportError: cannot import name 'raise_with_traceback'

### ISSUE THREAD

**Issue by franz101** [bashtage/arch#391]
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-19-2c446bf916e5> in <module>()
----> 1 from arch.covariance.kernel import Bartlett
      2 from arch.data import nasdaq
      3 data = nasdaq.load()
      4 returns = data[["Adj Close"]].pct_change().dropna()
      5 

8 frames
/usr/local/lib/python3.6/dist-packages/pandas/util/testing.py in <module>()
     26 
     27 import pandas._libs.testing as _testing
---> 28 from pandas.compat import _get_lzma_file, _import_lzma, raise_with_traceback
     29 
     30 from pandas.core.dtypes.common import (

ImportError: cannot import name 'raise_with_traceback'

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.

**Comment by bashtage** [comment]
That isn't a bug with ARCH.  I think your local configuration is not correct. You should try uninstalling pandas and reinstalling it.
