### ISSUE TITLE
help: type object 'arch.univariate.recursions.array' has no attribute '__reduce_cython__'

### ISSUE THREAD

**Issue by yecaohongdeng** [bashtage/arch#393]
[In]: from arch import arch_model
  Traceback (most recent call last):

  File "<ipython-input-101-f7e7e7ccf968>", line 1, in <module>
    from arch import arch_model

  File "F:\software\lib\site-packages\arch\__init__.py", line 2, in <module>
    from arch.univariate.mean import arch_model

  File "F:\software\lib\site-packages\arch\univariate\__init__.py", line 9, in <module>
    from arch.univariate.mean import ARX, HARX, LS, ConstantMean, ZeroMean, arch_model

  File "F:\software\lib\site-packages\arch\univariate\mean.py", line 14, in <module>
    from arch.univariate.base import (

  File "F:\software\lib\site-packages\arch\univariate\base.py", line 25, in <module>
    from arch.univariate.volatility import ConstantVariance, VolatilityProcess

  File "F:\software\lib\site-packages\arch\univariate\volatility.py", line 21, in <module>
    from arch.univariate.recursions import (

  File "stringsource", line 105, in init arch.univariate.recursions

Spyder 3.2.8 Python 3.6

**Comment by bashtage** [comment]
Could you post a more complete traceback?  This doesn't help me.

**Comment by yecaohongdeng** [comment]
Thanks for your reply. After installed arch by "pip install arch", I want to execute "from arch import arch_model" or "import arch", error happened.


The detailed description is attached. I really hope you can help me to solve this problem.


The problem was also met by other person, please open the link: https://stackoverflow.com/questions/56018451/how-to-import-arch-correctly-in-python


We had same problem.


Thank you very much!!!


















At 2020-05-29 13:29:02, "Kevin Sheppard" <notifications@github.com> wrote:

Could you post a more complete traceback? This doesn't help me.

**Comment by bashtage** [comment]
Which version of arch have you installed? Which version of python are you using?

**Comment by yecaohongdeng** [comment]
I solved this problem by use "conda install arch -c bashtage". The command I used previously is "pip install arch", maybe this caused some problem. But I have used "pip install xxx" to install some other packages. This is the first time I met such situation.

**Comment by bashtage** [comment]
I can't reproduce this error and you are the first to report it, so I'm going to close.
