### ISSUE TITLE
Can someone post an example for calculate the difference of Sharpe Ratio between two return series

### ISSUE THREAD

**Issue by weiguang-zz** [bashtage/arch#401]
As described by this [paper](http://www.ledoit.net/jef_2008pdf.pdf).  We can do a Hypothesis test on the difference of sharpe ratio between two return series using the bootstrap method.   however, It's too hard for me to implement the paper. I have found a very good [R library](https://github.com/ArdiaD/PeerPerformance). But can't find a python package.

I found a very good example on how to estimate the variance of the Sharpe Ratio and how to construct confidence intervals for the Sharpe Ratio at [this](https://arch.readthedocs.io/en/latest/bootstrap/bootstrap_examples.html), so I think this library should be a good tool to do this work.

Thank you very much.

**Comment by bashtage** [comment]
This is pretty old so I am going to close it.  stats stackoverflow is probably a better place for these types of questions.
