### ISSUE TITLE
Model forecasts evaluation

### ISSUE THREAD

**Issue by alfsn** [bashtage/arch#404]
Hi bashtage,

My objective is to calculate loss functions for the forecasts of the models (eg. Mean Squared Error).
eg. 
`mse = ((aux_df['forecast'] - variance)**2).mean()`

I am working with daily data for linear returns and 1 day horizon forecast.
What would be the conceptually appropriate variance to use in this calculation?

I have tried comparing it the 5 day rolling volatility, but only because it "looked right". 
![GGAL_ARCH_forecast_variance](https://user-images.githubusercontent.com/58914132/90719737-8fda4780-e28b-11ea-8be4-888771aacd30.png)

I have also tried Squared Returns (rescaled by a 10000 factor) but this also seems like "fudging" it.
![GGAL_ARCH_comparison](https://user-images.githubusercontent.com/58914132/90719792-aaacbc00-e28b-11ea-96e0-1cfc9ced367d.png)

Does this appropriate variance change if I use log returns for estimating the model?

I've read other threads on evaluation such as #213 #301 but did not seem to find an appropriate answer.
Some common estimators such as MSE or MAE could be useful in an evaluation phase.

Thanks in advance,
Kind regards,
Alfred

**Comment by bashtage** [comment]
When you are evaluating a variance forecast, you usually use the squared return as the proxy for the future variance.  This is typically noisy.  You can experiment with some simulated data where you know the true model which you can use to get a feel for things.

**Comment by alfsn** [comment]
Thank you!
