### ISSUE TITLE
Can't use "optimal_block_length" function

### ISSUE THREAD

**Issue by ringeringering** [bashtage/arch#407]
For whatever reason, I'm unable to utilize the optimal_block_length function to calculate the block length for a moving block bootstrap of my time series data. I clearly see that it is within the bootstrap/base.py file, but my Jupyter Notebook instance insists that it doesn't exist.

**Comment by bashtage** [comment]
What does arch.__version__ show?

**Comment by ringeringering** [comment]
'4.8.1'

**Comment by ringeringering** [comment]
I was able to update to version 4.15 (only through pip, I wasn't able to do so through conda), but now it seems to have gotten worse. I can't access arch.bootstrap and its methods at all now. I can still access arch.arch_model and the others though.

**Comment by simongarisch** [comment]
Hi there.

It looks like your version of arch does not include the optimal_block_length function.
It's in the latest [version](https://github.com/bashtage/arch/blob/ab7536a546976526fce31557ebffeaed690502cf/arch/bootstrap/base.py#L96) so you can fetch it with a:
```bash
pip install --upgrade arch
```

Here it is with the latest version:
```bash
>>> import arch
>>> arch.__version__
'4.15'
>>> from arch.bootstrap import optimal_block_length
>>> optimal_block_length
<function optimal_block_length at 0x0000016EF5094310>
>>>
```

But missing with your version:
```bash
>>> import arch
>>> arch.__version__
'4.8.1'
>>> from arch.bootstrap import optimal_block_length
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'optimal_block_length'
```

Cheers

**Comment by ringeringering** [comment]
@simongarisch Thank you for the response, that resolved my issue. For whatever reason the first time I upgraded my version to 4.15 the entire bootstrap library wasn't showing up, but after trying again in response to your question it worked out. Thanks again!
