### ISSUE TITLE
Question about the arch package

### ISSUE THREAD

**Issue by mrajancsr** [bashtage/arch#409]
Hello Professor,
Thanks for your package.  I'm replicating a research paper and had to utilize the garch(1,1) model.  I do have the bad habit of implementing many things from scratch only to validate my own understanding of a model.  A couple of questions I had with your garch(1,1) model as I compared with mine were;
-I assumed 0 mean out of simplicity.  If mean is not zero(conclusion from one sample t-test),I remove it from my returns series.  
2) for MLE estimation, are you using QMLE?  
2) starting values for volatility-I assumed unconditional variance, but changed it to variance of returns (returns - mu).  
3) starting values for parameters of optimization- bounds are for omega, (0, None), gamma = (0,1) and beta = (0,1).  

Starting values are (ret.var(), 0.09, 0,9). 
4) I even derived the gradient of the log-likelihood which ended up being a recursive first order difference equation.  Put that into my optimizer to speed it up. 

So after all this, I created a simulated garch model with parameters (0.1,0.2 and 0.3) and tested my model.  After fitting, my implementation and yours matched.  But I could have gotten lucky as my starting values were closer to the models true parameters.  Albeit yours was much faster.  

I then tried to fit it against a log return series and found much difference in our estimated parameters and am curious how can this be possible?  In your model, the omega parameter was at 3.10.  Mine was at 0.000680.  

And in any case, the conditional volatility in your model was much different than the long term conditional variance as stipulated by garch (1,1) formula.  

5) are you using different starting values for your volatility?  

Thanks and sorry for this long question.

**Comment by bashtage** [comment]
It is QMLE whenever the distribution is misspecified, but arch does default to the QMLE robust standard errors.


Can you post the code that simulates the log returns and the call to the arch model so I can see?

**Comment by mrajancsr** [comment]
@bashtage , thanks for your reply.  I managed to get my numbers to match with yours.  They are pretty similar now.  Thanks for your reply.  Not sure why the numbers were different before as im not able to reproduce the error.  If i come across it, i will raise an issue.  Thanks.  closing it now as its solved.
