### ISSUE TITLE
How to use the package for ARMA-GARCH

### ISSUE THREAD

**Issue by ramdhan1989** [bashtage/arch#410]
I have cash change daily data that show volatile behaviour which can fall between huge positive and negative values. I need to forecast 1 step ahead. I try to use GARCH model from pyflux but it seems the prediction error is huge. I read that ARMA-GARCH is worth to try. I have some questions as follow.

1. does this package incorporate ARMA-GARCH directly? what do you think about the implementation here :
[https://stats.stackexchange.com/questions/421245/arma-garch-python-implementation](url)
link above try to combine prediction of mean using ARIMA and fitted ARIMA residual using GARCH. and get back prediction by adding both of model output. I don't know this method is correct or not since there is drawback using this method as discussed here. 
[https://stats.stackexchange.com/questions/252449/specifying-an-arma-garch-model-without-rugarch](url)

what do you think? do we need to do two step approach or just using this package directly and it will handle the rest ?

2. If I have daily data with missing values , do we need to drop them ? or the implementation requires complete data without missing values (need data imputation). the stock prices case in this repo seems drop rows with null values so there is a gap in the dataset.

Plese advice,

thank you

**Comment by bashtage** [comment]
I have never implemented that MA part of an ARMA.  You can fit AR-GARCH, but not ARMA-GARCH. 

1. The answer in 1 is correct.  You can filter using ARMA, then model the volatility using mean-zero residuals. The drawback is that the parameters are not efficiently estimated. The second drawback is that forecasts have to be manually recomputed.
2. ARCH-type models require full data.  The common practice is to drop them, e.g., weekends and holidays are typically dropped.  This is, of course, a modeling decision.

**Comment by ramdhan1989** [comment]
well noted thank you for you advice
