### ISSUE TITLE
HARX lags document wrong

### ISSUE THREAD

**Issue by guoxuesong** [bashtage/arch#411]
```
`    lags : {scalar, ndarray}, optional
        Description of lag structure of the HAR.  Scalar included all lags
        between 1 and the value.  A 1-d array includes the HAR lags 1:lags[0],
        1:lags[1], ... A 2-d array includes the HAR lags of the form
        lags[0,j]:lags[1,j] for all columns of lags.

```

1:lags[0] should be changed to 0:lags[0] etc

**Comment by bashtage** [comment]
I believe is this is correct.  What makes you think it is wrong? 

```
lags = [1,5,22]```

will build a model with averages using y_t-1, {y_t-1,...y_t-5}, and {y_t-1,...,y_t-22}.

The only thing that is a bit wrong is the slice. It should really be 
```
    lags : {scalar, ndarray}, optional
        Description of lag structure of the HAR.  Scalar included all lags between 1 and the value. 
        A 1-d array includes HAR lags terms using observations 1,2,...,lags[0], 1,2,...,lags[1], ... 
        A 2-d array includes the HAR lags of the form lags[0,j],lags[0,j]+1,...,lags[1,j] for all columns
        of lags. Note that the end points are inclusive in both array specifications.
```

**Comment by guoxuesong** [comment]
On my understanding of the code, lags = [1,5,22] equals to lags = [[0,0,0],[1,5,22]]. Is this correct ?

Code in _reformat_lags :

```
        if lags.ndim == 1:
            if np.any(lags <= 0):
                raise ValueError(
                    "When using the 1-d format of lags, values must be positive"
                )
            lags = np.unique(lags)
            temp = np.array([lags, lags])
            if self.use_rotated:
                temp[0, 1:] = temp[0, 0:-1]
                temp[0, 0] = 0
            else:
                temp[0, :] = 0
            self._lags = temp
```

According to the document, lags = [1,5,22] should equal to lags = [[1,1,1],[1,5,22]] .

**Comment by bashtage** [comment]
Yes, I agree with that.  Do you not thing the documentation agrees with
this interpretation?

**Comment by guoxuesong** [comment]
Acording to the code:  lags = [1,5,22] equals to lags = [[0,0,0],[1,5,22]].
Acording to the document: lags = [1,5,22] equals to lags = [[1,1,1],[1,5,22]].

I think there is a conflict between the code and the document.

**Comment by bashtage** [comment]
This is a bug.
