### ISSUE TITLE
Trend 'nc' not working

### ISSUE THREAD

**Issue by yingpublic** [bashtage/arch#413]
Hi, I've tried different trend setting. eg 'c', 'ct', 'ctt' and 'nc'. Three of them are working but 'nc' gives me the following message. Is this a bug?

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-41-4120a7ebb47d> in <module>()
          3 series = da_test_all[:,39,60]
          4 adf = ADF(series)
----> 5 adf.trend = 'nc'     #'nc' : No deterministic terms
          6 print(adf.summary().as_text())

/usr/local/lib/python3.6/dist-packages/arch/unitroot/unitroot.py in trend(self, value)
       650     def trend(self, value: str) -> None:
       651         if value not in self.valid_trends:
--> 652             raise ValueError("trend not understood")
      653         warnings.warn(MUTATING_WARNING, FutureWarning)
      654         if self._trend != value:

ValueError: trend not understood

**Comment by bashtage** [comment]
What about "n"?

**Comment by bashtage** [comment]
https://bashtage.github.io/arch/unitroot/generated/arch.unitroot.ADF.html

**Comment by bashtage** [comment]
Closing as answered.  If you have any other issues, please let me know.
