### ISSUE TITLE
Understanding return types of 'forecast()' using different distributions

### ISSUE THREAD

**Issue by mberaha** [bashtage/arch#423]
Hi,

as a part of a larger project, I want to get full distributional forecast (not only mean and variance).
If I fit the normal model, things are easy because I can just get the mean and variance parameters directly from the forecasting and then compute the density:
```
model = arch_model(returns, mean="LS", vol="GARCH", p=1, q=1).fit()
yhat = arch_mod.forecast(horizon = 1)
mean = yhat.mean.values[-1, 0]
sd = np.sqrt(yhat.variance.values[-1, 0]))
xgrid = np.linspace(-10, 10, 100)
distrib_prediction = scipy.stats.norm.pdf(xgrid, mean, sd)
```

However, when specifying the model with `dist="t"` I would need to understand the correct parametrization of the underlying distribution. In particular, what is the number of degrees of freedom in the student's t distribution?
Is there a way of evaluating this distribution on a grid as in the normal case?

**Comment by bashtage** [comment]
> In particular, what is the number of degrees of freedom in the student's t distribution?

Normally you estimate this parameter when you are estimating the parameters of your model.

> Is there a way of evaluating this distribution on a grid as in the normal case?

For a given DoF value `nu`, ` scipy.stats.t(nu,scale=np.sqrt((nu-2)/nu))` is a standardized Student's t.

**Comment by mberaha** [comment]
Thanks for the super-quick reply!
Just so that I don't get things wrong, in the model with `dist=t`, the probabilistic model for observations r_t is:
r_t = mu + epsilon_t
epsilon_t = sigma_t * e_t
sigma_t ^ 2 = omega + alpha * espsilon_t ^ 2 + beta * sigma_t ^ 2

where e_t are iid variables distributed as a student's t with `nu` degrees of freedom, and `nu` is estimated as well?

Hence the distribution of epsilon_t is a scaled student t, with scale given by sigma_t? And the value returned by yhat.variance.values[-1, 0], is `sigma_t` or  `nu / (nu-2) * sigma_t ** 2`

**Comment by bashtage** [comment]
> where e_t are iid variables distributed as a student's t with `nu` degrees of freedom, and `nu` is estimated as well?

e_t are standardized Student's t(nu) RVs which have the property that E[e_t^2] = 1 for all possible values of nu.

epsilon_t is then distributed Standardized Student's t (0,sigma_t^2,nu) so that E[epsilon_t^2]=sigma_t^2.

See:

https://bashtage.github.io/arch/univariate/generated/generated/arch.univariate.StudentsT.loglikelihood.html#arch.univariate.StudentsT.loglikelihood

for the log density.

**Comment by mberaha** [comment]
Thank you so much!
