### ISSUE TITLE
date_index must be a datetime64 array when defining start attribute in forecast

### ISSUE THREAD

**Issue by rahulgupta3009** [bashtage/arch#424]
Hi all,

I have gone through the documentation tutorials and structured my returns series the same way with percentage change. Defining my model object goes as smooth as possible and model fitting is fine too.

While forecasting, I am able to define the horizons that I want but when I try and define the start attribute with a string/datetime object/numpy datetime64 object, I get error and am not able to proceed further. I am trying to run a VaR model eventually. 

Python - 3.7
arch - 4.15
OS - Windows 10

PFA the code snippet and error.

`garch_model_forecast = garch_model_result.forecast(start = '2018-1-1')`

Error ------

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-117-9291752511e5> in <module>
----> 1 garch_model_forecast = garch_model_result.forecast(start = '2018-1-1')

D:\Anaconda\envs\arch_model\lib\site-packages\arch\univariate\base.py in forecast(self, params, horizon, start, align, method, simulations, rng, random_state)
   1392             raise ValueError("horizon must be an integer >= 1.")
   1393         return self.model.forecast(
-> 1394             params, horizon, start, align, method, simulations, rng, random_state
   1395         )
   1396 

D:\Anaconda\envs\arch_model\lib\site-packages\arch\univariate\mean.py in forecast(self, params, horizon, start, align, method, simulations, rng, random_state)
    698         earliest, default_start = self._fit_indices
    699         default_start = max(0, default_start - 1)
--> 700         start_index = cutoff_to_index(start, self._y_series.index, default_start)
    701         if start_index < (earliest - 1):
    702             raise ValueError(

D:\Anaconda\envs\arch_model\lib\site-packages\arch\utility\array.py in cutoff_to_index(cutoff, index, default)
    248     int_index = default
    249     if isinstance(cutoff, (str, dt.datetime, np.datetime64, Timestamp)):
--> 250         int_index = date_to_index(cutoff, index)
    251     elif isinstance(cutoff, int) or issubclass(cutoff.__class__, np.integer):
    252         assert cutoff is not None

D:\Anaconda\envs\arch_model\lib\site-packages\arch\utility\array.py in date_to_index(date, date_index)
    188     """
    189     if not is_datetime64_any_dtype(date_index):
--> 190         raise ValueError("date_index must be a datetime64 array")
    191 
    192     if not np.all((np.diff(date_index.values).astype(dtype=np.int64)) > 0):

ValueError: date_index must be a datetime64 array

**Comment by bashtage** [comment]
Can you provide a more complete example. Ideally, one I can copy and paste to reproduce the error?  Feel free to use simulated data.

**Comment by bashtage** [comment]
This works as expected for me:

```
import pandas as pd
from arch.univariate import HARX, arch_model

am = arch_model(None)
data = am.simulate([0.1, 0.1, 0.1, 0.8], nobs=1000)
data.index = pd.date_range("2020-1-1", periods=1000)
mod = arch_model(data.data)
res = mod.fit()
fcast = res.forecast(horizon=10, start="2022-09-22")
```

I'm going to close since there doesn't appear to be a bug.  If you still have an issue, please post code that can reproduce the error.
