### ISSUE TITLE
BUG: Expose x in forecasting 

### ISSUE THREAD

**Issue by ganeshramg** [bashtage/arch#425]
Hey team, I include X_train in exogenous variables parameter in model constructor, and y_train for the dependent variable, and mean='HARX' and all other necessary params. Now, while forecasting how do I use X_test in the code after which I'll be able to compare the forecasts with y_test for further evaluation. Kindly help. I'd appreciate some advice on how to use HARX model, as I'm used to Sci-Kit learn APIs. Thanks :)

**Comment by bashtage** [comment]
Can you post a code example that shows what you are doing?

**Comment by ganeshramg** [comment]
![garch](https://user-images.githubusercontent.com/42694700/101976243-457d3c00-3c69-11eb-8fd9-e00da161ad4b.PNG)

Here, there are four sets of preprocessed data, namely, X_train, y_train, X_test, and y_test. Now, I specify the univariate target as y_train, and the required additional exogenous known regressors as X_train in the 'x' parameter of the constructor, along with mean = 'HARX' for heteroskedasticity and exogenous variables. I'm stuck at the prediction part, where the horizon parameter is pretty straight forward and my required length is len(y_test), but how do I include the X_test as regressors for the prediction part? Appreciate your help

**Comment by bashtage** [comment]
I think this is a bug and there is no way to pass x when forecasting.
