### ISSUE TITLE
HARX forecast returns only NaN with exogenous variable

### ISSUE THREAD

**Issue by KristianLeino** [bashtage/arch#435]
I'm trying to forecast one-step with HARX with an exogenous variable, but the forecast method returns only NaN. What might be the problem? 

E.g.

df = pd.DataFrame(np.random.randint(0,100,size=(1000, 2)), columns=list('YX'))
mod = arch.univariate.HARX(y=df['Y'],x=df['X'],lags=[1,5,22])
res = mod.fit(disp='off')
har_forecast = res.forecast()
forecast = har_forecast.mean['h.1'].iloc[-1]
print(forecast)

**Comment by bashtage** [comment]
This is the same as #425 I think. There is no way to pass exog values for forecasts.
