### ISSUE TITLE
DOC: Using returns instead of log-prices

### ISSUE THREAD

**Issue by tchew86** [bashtage/arch#439]
Dear Kevin,

please check the example given in the comments to the VarianceRatio().

https://github.com/bashtage/arch/blob/3b017865aecf45e74cc91628a27a2496a835e6e0/arch/unitroot/unitroot.py#L1622

There, returns of the Dow Jones are used as inputs for the function. However, the function code follows Lo/MacKinley and expects log Prices (as returns as calculated as log price differences).

Best
Thomas

**Comment by bashtage** [comment]
While the example isn't technically incorrect (one can test any series using a VR), I agree that it would be more sensible to use log prices.
