### ISSUE TITLE
Compatibility Issue with newer versions of Numpy

### ISSUE THREAD

**Issue by badali16** [bashtage/arch#450]
There appears to be a compatibility issue with newer versions of Numpy.

The following error is raised when the arch package is imported:

"ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject"

This seems to be a common issue related to some newer versions of Numpy.

On a separate note this library is great - the interface is excellent.  Thanks to all those who contributed to this.

**Comment by bashtage** [comment]
I thini it is a NumPy issue mostly.

**Comment by bashtage** [comment]
Are you using Anaconda?

**Comment by badali16** [comment]
Yes, but I used the online install instructions.  The error appeared after trying both pip and conda.  I'm a novice with packages but my guess was numpy version issues after a few google searches.

**Comment by badali16** [comment]
You are correct it was an environment issue.  My guess is that it's related to installing packages with a mixture of conda and pip.

pip install numpy --upgrade --force-reinstall
pip install arch --force-reinstall

Note, if you don't want to upgrade you may need to uninstall explicitly
