### ISSUE TITLE
Specifying an initial volatility for a constant mean GARCH(1,1)

### ISSUE THREAD

**Issue by bennje** [bashtage/arch#452]
Hello,

How can I specify an initial squared volatility that is a function of the current parameter values? In particular I am interested in one of the two following (motivated by GARCH Models (2010), by C. Francq et al., p. 142).

1. sigma_0^2 = epsilon_0^2 = current omega parameter
2. sigma_0^2 = epsilon_0^2 = (return_1 - mu)^2, where mu is the current mean parameter

Basically as the parameters are changed in the optimization procedure I want sigma_0^2 to change accordingly based on the current estimates.

I apologize if this is easily seen from the documentation. For some reason I have not been able to figure it out even after reading it for a few hours.

**Comment by bashtage** [comment]
Setting the backcast with a function of parameters is not possible.  You can probably do this pretty easily by subclassing the GARCH and then changing the lines here to dynamically back-cast:

https://github.com/bashtage/arch/blob/592058e619ded215bc04ad1d53893bd6acfd10b5/arch/univariate/volatility.py#L1024

**Comment by bashtage** [comment]
You could also probably do the second version by iterating a few times (probably 2).

1. Estimate GARCH model with standard backcast
2. Then set `backcast=(r[0] - params.mu)**2`

You could iterate on 2 until it converges.

**Comment by bashtage** [comment]
You could probably do the same for omega as well, but it may take more iterations since changing the backcast make have a larger impact on omega.

**Comment by bennje** [comment]
Thank you for pointing me in the right direction.
