### ISSUE TITLE
Forecast components: conditional variance and residual variance

### ISSUE THREAD

**Issue by chintanr97** [bashtage/arch#459]
I am using `arch` library to build ARCH/GARCH models on time-series. After fitting the model (GARCH(p, q) model with constant mean), I run the simulation-based forecasts for a short horizon period. 

`forecasts = eres.forecast(horizon=5, method='simulation', simulations=100)`

After this, I print the forecast conditional variance and residual variance without the `NaN` values. I am following the given [link][1] to understand the meaning of `conditional variance` and `residual variance`.

The output for `conditional variance` and `residual variance` turn out to be exactly the same. However, I am not able to understand the reason for this. Quoting the snippet from above link:

> `residual_variance` - The forecast conditional variance of residuals.
> This will differ from `variance` whenever the model has dynamics (e.g.
> an AR model) for horizons larger than 1.

What does *dynamics* mean intuitively? 
Mathematically, how is the package calculating these values and why are they turning out to be the same?

Any pointers would be really helpful!

Regards,
Chintan Rajvir

  [1]: https://arch.readthedocs.io/en/latest/univariate/forecasting.html#understanding-forecast-output

**Comment by bashtage** [comment]
Dynamics means AR coefficient.  In an AR(1), Y(t) = a + b Y(t-1) + epsilon(t), if the conditional variances of epsilon(t+j) for j=1,2,3 are s1, s2 and s3, then the conditional variance is s1, b**2*s1+s2, b**4*s1+b**2*s2+s3.  The difference is that conditional variance is the conditional variance of process, V[Y(t+h)| I_{t}], while the residual variance is V[epsilon(t+h)|I_{t}] where I_{t} is the time t information set.

Does this clarify the difference?

**Comment by chintanr97** [comment]
I understood the mathematical part. But I would like to know about any pointers which would help me identify its derivation for any forecast length `j`. Like, if residual variance at `j=2` is `s2`, then which steps lead us to the conditional variance being `pow(b,2)*s1 + s2`. 

And additionally, I am understanding that if we train GARCH model on original time series, then the modelled volatility process is the `conditional volatility` of the original time series v/s if we train GARCH model on squared-residuals of ARIMA, then the modelled volatility process is the `conditional volatility of squared-residuals`. Please correct me if I misinterpreted it.

**Comment by bashtage** [comment]
You should look in a time series textbook for the derivation. It is probably in Walter Enders Applied Economic Time Series.  It is a standard result for forecast errors in ARMA models. The result is not particularly complex but is tedious without some linear algebra setup.

Normally you would either fit the model to the data directly and incorporate the mean as part of the model, or you would model the mean using some process and then model the residuals of that process as a zero-mean GARCH process.  You would not normally pass in the squared residuals to the arch model.

If you did pass the squared residuals then these become `y`, and so the mean model in an arch model is now the mean of the squared residuals and the variance is the variance of the squared residuals, which would be related to the kurtosis of the original data.

**Comment by chintanr97** [comment]
Thank you @bashtage! This was helpful!
