### ISSUE TITLE
future feature annotations is not defined

### ISSUE THREAD

**Issue by felipemoz** [bashtage/arch#482]
Hello everyone,
I've tried to install and use arch directly from git directly on Anaconda 3.6:

Steps to reproduce:

`!pip3 uninstall enum34 -y & pip3 install pyinstaller -y & pip3 install git+https://github.com/bashtage/arch.git 
`

```
Traceback (most recent call last):

  File "/anaconda/envs/azureml_py36/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3343, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-29-f7e7e7ccf968>", line 1, in <module>
    from arch import arch_model

  File "/anaconda/envs/azureml_py36/lib/python3.6/site-packages/arch/__init__.py", line 2, in <module>
    from arch.univariate.mean import arch_model

  File "/anaconda/envs/azureml_py36/lib/python3.6/site-packages/arch/univariate/__init__.py", line 1
    from __future__ import annotations
                                      ^
SyntaxError: future feature annotations is not defined
```

The conda install does not work pretty well :/

**Comment by bashtage** [comment]
Which Python are you using?

I think it is 3.7 minimum now.

**Comment by felipemoz** [comment]
This is conda python 3.6, provided by: Azure ML, AWS Sagemaker, Google Colab.

**Comment by bashtage** [comment]
You will need to use Python 3.7 or newer, or limit the version to Arch 4.18 (I think should work, may be 4.17).

**Comment by bashtage** [comment]
You should be able to create a virtual env I suspect with a later Python, e.g.

```
conda create -n virtenv python=3.8
```

**Comment by felipemoz** [comment]
I'm quite sure that is not possible to change on Jupyter interface. Doing some searchs.

**Comment by crayonfu** [comment]
> 
> 
> I'm quite sure that is not possible to change on Jupyter interface. Doing some searchs.

On Jupyter (Lab/Notebook) top right corner there is a button to change kernel. Choose any python in system or virtual env from the dropdown menu.

**Comment by bashtage** [comment]
https://docs.microsoft.com/en-us/azure/machine-learning/how-to-run-jupyter-notebooks#change-the-notebook-environment
