### ISSUE TITLE
Implementing Stratified Bootstrap

### ISSUE THREAD

**Issue by agarwl** [bashtage/arch#484]
Hi,

I'd like to implement a stratified sampling version of the bootstrap -- I have a population of `n` samples for `k` classes (or labels) each and I'd like to maintain equal number of samples per class in the bootstrap samples. 

Can you provide any pointers on how to modify the `IIDBootstrap` class to implement this?

Regards,
Rishabh

**Comment by bashtage** [comment]
You could follow the pattern here:

https://github.com/bashtage/arch/blob/5bcdae4ba5312de88be80471d93e397767f22450/arch/bootstrap/base.py#L1310

An `__init__` something like

```python
class StratifiedBootstrap(IIDBootstrap):
    _name = "Stratified Bootstrap"
    def __init__(
        self,
        labels: Union[Sequence[int], ndarray, pd.Series],
        *args: ArrayLike,
        random_state: Optional[RandomState] = None,
        **kwargs: ArrayLike,
    )
``` 

The only things you really need to override is  `update_indices` which would generate the stratified sample.  

https://github.com/bashtage/arch/blob/5bcdae4ba5312de88be80471d93e397767f22450/arch/bootstrap/base.py#L1406

The remainder of the methods should work as expected.

**Comment by bashtage** [comment]
You would then use it like
```python
import numpy as np

lbl = [i%10 for i in range(1000)]
data = np.random.standard_normal((1000,10))
sb = StratifiedBootstrap(lbl, data)
```

**Comment by agarwl** [comment]
Thanks for the detailed and quick reply!

**Comment by bashtage** [comment]
Happy to take a PR to add this if you want.

**Comment by agarwl** [comment]
My use case was limited and this worked for me (This isn't general enough though):

```
class StratifiedBootstrap(IIDBootstrap):
  _name = "Stratified Bootstrap"
  def __init__(
      self,
      *args: ArrayLike,
      num_strata: Optional[int] = None,
      random_state: Optional[RandomState] = None,
      **kwargs: ArrayLike,
  ) -> None:
    super().__init__(*args, random_state=random_state, **kwargs)
    # The inputs are assumed to be of the shape `(num_samples, num_strata, ..)`.
    if num_strata is None:
      num_strata = args[0].shape[1]
    else:
      self._num_strata = num_strata
    self._parameters = [num_strata]
    self._strata_indices = self._get_strata_indices()

  def _get_strata_indices(self):
    indices = np.expand_dims(np.arange(self._num_strata), axis=0)
    return np.repeat(indices, self._num_items, axis=0)

  def update_indices(
      self,
  ) -> Union[NDArray, Tuple[List[NDArray], Dict[str, NDArray]]]:
    indices = np.random.choice(
        self._num_items, (self._num_items, self._num_strata),
        replace=True)
    return (indices, self._strata_indices)
```

**Comment by agarwl** [comment]
For anyone who's looking for stratified bootstrap, refer to the implementation based on arch in [rliable](https://github.com/google-research/rliable).
