### ISSUE TITLE
Backcast treated incorrectly in EGARCH simulation forecast

### ISSUE THREAD

**Issue by romango** [bashtage/arch#485]
The backcast in EGARCH seems to be in log(variance) units based on how its used in recursions.pyx. Therefore the backcast in EGARCH may be negative. This is causing a log-of-negative error in the following line:

https://github.com/bashtage/arch/blob/5bcdae4ba5312de88be80471d93e397767f22450/arch/univariate/volatility.py#L2638

Here, I believe a log is being taken of the backcast under the erroneous assumption that it is a variance number.

**Comment by bashtage** [comment]
Thanks for reporting -- this is definitely a bug.
