### ISSUE TITLE
Python 3.6 and version 4.19

### ISSUE THREAD

**Issue by ovrt4848** [bashtage/arch#490]
Is anyone else having issues updating to version 4.19 using python 3.6?  I believe the "from __future__ import annotations" is causing the backwards capability problems?

**Comment by bashtage** [comment]
That sounds right.  I should remove all mention of 3.6 which is not tested, and clearly not supported.

**Comment by bashtage** [comment]
At this point the only viable solution is to move to Python >= 3.7.
