### ISSUE TITLE
References for Univariate Volatility Models

### ISSUE THREAD

**Issue by lukedyer-peak** [bashtage/arch#493]
I was wondering if you had any introductory references or lecture notes for the _Univariate Volatility Models_ part of this package.  I noticed that the background & reference section is TBC.  I was hoping that you might have some up your sleeve 🤞 .  Thanks.

**Comment by bashtage** [comment]
Chapter 7 of [my notes](https://www.kevinsheppard.com/teaching/mfe/notes/) provides a graduate level introduction.  [Brooks' book](https://smile.amazon.co.uk/Introductory-Econometrics-Finance-Chris-Brooks/dp/110843682X) provides a less dense introduction.

**Comment by lukedyer-peak** [comment]
Brilliant thanks!  (I've got a maths background so a grad level intro is a nice starting point)
