### ISSUE TITLE
Passing custom distribution or innovation values to forecast

### ISSUE THREAD

**Issue by rskene** [bashtage/arch#507]
I am working a project similar to [this](https://ww2.mathworks.cn/help/econ/using-extreme-value-theory-and-copulas-to-evaluate-market-risk.html;jsessionid=9d131a7cc439551428e2cfc5569b
), essentially attempting to fit fat tails to the standardized residuals of whatever AR/GARCH model you choose. I am using a two-tailed pareto, only difference from tutorial above is mine is continuous through the body.

For go-forward simulation, they produce the residuals from the two-tailed model and pass them to this [filter function](https://www.mathworks.com/help/econ/garch.filter.html), which works just like the `forecast`/`simulate` functions on the models in this package, except the residuals are passed by the user and not generated automatically (looks like `rng` parameter is used to generate these from the various supported distributions).

It looks like this could be accomplished just by hooking into, for instance, `std_shocks = rng((simulations, horizon))` in the `_simulation_forecast` of GARCH, for example.

First, wondering how sound this method is. Strikes me that if the AR/GARCH is fit with N(0,1) assumed as error term then providing `rng` from another distribution in the forecast would mean at least some portion of the residual was being "double-counted" in a sense.

Second, wondering how it might best be implemented. Thinking I could just subclass DIstribution and then provide a `simulate` call as the rng parameter in a forecast ...................

**Comment by rskene** [comment]
Should also say, excellent package, very fast!

**Comment by bashtage** [comment]
There are two options. 

1. Write your own distribution.  You can use https://github.com/bashtage/arch/blob/main/arch/univariate/distribution.py as a template and implement the required functions. This can then be used in estimation and simulation. 
2. Estimate using one of the known distributions, but follow the scenario guide to pass a custom generator.  https://bashtage.github.io/arch/univariate/univariate_volatility_scenarios.html#Custom-Random-Generators

**Comment by rskene** [comment]
Excellent, thank you. Could I pass the distribution in or will I have to pull and add it?

Also, any comment on the rigor of this approach? The note is made here: 

"A shock generator should usually produce unit variance shocks"

I wonder if one incorporates too many such shocks if it invalidates the sequence fit?

**Comment by bashtage** [comment]
You can write your own distributions or rngs and keep them local.  If you want to write a complete distribution PRs are welcome.

The usual identifying assumption of an ARCH model is that `E[e^2_{t+1}|F_t]=1`  where `e_{t+1}` is the standard shock at time period 1. All of the included distributions have this property.
