### ISSUE TITLE
Out-of-sample forecasts

### ISSUE THREAD

**Issue by rskene** [bashtage/arch#508]
One last question for today ;)

The 'simulation' method for `forecast` is very simple and fast. Just curious why it isn't built to forecast beyond the last index of the dataset?

is it possible to, say, if you want to forecast 30 days beyond the current dataset, you could simply add 30 days to the dataset with `np.nan` or `0` and set the `last_obs` to the last day of actual data? I've tried this and the forecasts come out alot different than the in-sample ones. Seems like the residuals from the entire dataset are getting incorporated into a few things, like `compute_variance` maybe, whether they are actually being used to fit or not.

Anyway, just wondering if there's a best way to do this. Kind of looking like, if one wants to do, say, 1,000 sims of 30 days forward forecasted, a new model would need to be instantiated and fit 30x1000 = 30,000 times .....

**Comment by bashtage** [comment]
It defaults to making out-of-sample forecasts.

```python
import datetime as dt
import arch.data.sp500
from arch import arch_model
from arch.__future__ import reindexing
import matplotlib.pyplot as plt
import seaborn

st = dt.datetime(1988, 1, 1)
en = dt.datetime(2018, 1, 1)
data = arch.data.sp500.load()
market = data["Adj Close"]
returns = 100 * market.pct_change().dropna()

am = arch_model(returns)
res = am.fit(update_freq=5)
# 22-say ahead forecasts
f = res.forecast(horizon=22, method="simulation")

f.variance
```
which produces
```
               h.01      h.02      h.03      h.04      h.05      h.06  \
Date                                                                    
2018-12-31  3.59647  3.550389  3.513709  3.508162  3.477808  3.461138   

                h.07      h.08      h.09      h.10  ...      h.13     h.14  \
Date                                                ...                      
2018-12-31  3.436541  3.414439  3.362262  3.345084  ...  3.287531  3.26197   

                h.15      h.16      h.17      h.18     h.19      h.20  \
Date                                                                    
2018-12-31  3.224731  3.202415  3.185306  3.191365  3.18131  3.179292   

                h.21      h.22  
Date                            
2018-12-31  3.159906  3.118144
```

You only need one model to produce a sequence of 30-day forecasts. 

You can also see all of the forecast paths using `f.simulations.variances` which is an array with shape (1,1000,22) -- that is, 1000 simulations of 22 days ahead.

Or do you want to make 30 1-day ahead forecasts?

**Comment by rskene** [comment]
Ya, so I've been misunderstanding the in-sample forecast. I guess if you are training on, say, all but the last 10 observations and you run a forecast with `horizons=1`, the output is a series of 10 consecutive 1-day forecasts, not a 10-day forecast from the end of training.

For out-of-sample on the horizon dimension, i guess the idea is there isn't a residual, but if you are incorporating shocks from, say, fat tails there would be, so wondering if a loop could be used where the residual from the last one step-ahead forecast is included in the next step-ahead forecast and avoid re-fitting with each loop. seems like this could be done by instantiating `GARCH` directly and looping  through `forecast` calls. 

seems like maybe this is what is contemplated by the `update` method?

**Comment by rskene** [comment]
Now after hitting send, strikes me that the `std_shocks` are being incorporated with each `horizon` loop, so that should result in the horizon paths being less smooth / more "natural" over time ... so maybe updating the residuals won't have much of an effect. and maybe updating the residuals would actually be a bad idea b/c the two processes (the AR-GARCH and the shocks) would be mixing over time.

Sorry, just helpful for me to work through these things!

**Comment by bashtage** [comment]
> Ya, so I've been misunderstanding the in-sample forecast. I guess if you are training on, say, all but the last 10 observations and you run a forecast with `horizons=1`, the output is a series of 10 consecutive 1-day forecasts, not a 10-day forecast from the end of training.

This is right.  You can have a sequence of any horizon though, not just 1.  1 is just the default.

> For out-of-sample on the horizon dimension, i guess the idea is there isn't a residual, but if you are incorporating shocks from, say, fat tails there would be, so wondering if a loop could be used where the residual from the last one step-ahead forecast is included in the next step-ahead forecast and avoid re-fitting with each loop. seems like this could be done by instantiating GARCH directly and looping through forecast calls.

I don't really understand what you are trying to accomplish.  Could you use some code/psuedo code to explain the existing approach and what you would like?  You can use the same parameters easily by creating a sequence of models but only estimating the first.

In theory this should work, but I am getting an exception (which I will fix).

```python
from arch.__future__ import reindexing

from arch.univariate import ConstantMean, GARCH
from arch.data.sp500 import load
sp500 = 100 * load()["Adj Close"].pct_change().dropna()

vol = GARCH()
base = ConstantMean(sp500.iloc[:-10], volatility=vol).fit(disp=False)
params = base.params
fcasts = {}
for i in range(11):
    mod = ConstantMean(sp500.iloc[:-10+i], volatility=vol)
    fcasts[i] = mod.forecast(params)
```

This should be equivalent to setting the last_obs and then creating all of the out-of-sample forecasts.

**Comment by bashtage** [comment]
I checked in #509 and using a reduced size sample and setting `first_obs` and `last_obs` are identical. This simplifies producing many out-of-sample forecasts using a single model fit.

**Comment by rskene** [comment]
Thanks for the help. I just misunderstood how the `horizon` forecast worked. It does seem like it feeds the residuals forward from t=1 to t=n.

Relative to the Mathworks tutorial, I think I just have a theoretical problem now. If you try to substitute an entire distribution that doesn't have Var = 1 (as you said earlier), the volatility becomes unstable. So there's no way they just pass in the random draws from the fat tails and use those as e_t. And if they are normalizing them to Var=1, well, they aren't really fat tails anymore.

Perhaps they just add it as an extra term.

**Comment by bashtage** [comment]
Why don't your residuals have var =1?  The only reason I could imagine one would try this would be if the standardized residuals have infinite variance.   But then the 2-step forecast will not be finite, so instability is expected.

**Comment by bashtage** [comment]
In GARCH models, the 1-step forecast is always known at the end of the sample and so no residual is used to simulate the 1-step forecast. Residuals are only used for 2-steps or longer.

**Comment by rskene** [comment]
Maybe I am mixing terms improperly here.

I mean the standardized residuals after the GARCH fit. If I fit a GARCH to S&P500 returns, the GARCH doesn't exactly mimic the S&P 500 returns. There are error terms still and those error terms don't have Var=1. Presumably the standardized error terms don't have Var=1 either.

And, as I understand it, or at least how it's done in the Mathworks tutorial, you can fit a distribution to those error terms, standardizing by dividing the error by the conditional volatility. But if you generate random draws from the distribution and use those as e_t in the GARCH, it becomes unstable (because the distribution doesn't have Var=1).

So they must be just adding them separately from the GARCH process ...........

**Comment by bashtage** [comment]
They won't have variance exactly 1 but should be very close. 

https://bashtage.github.io/arch/univariate/generated/generated/arch.univariate.base.ARCHModelResult.std_resid.html#arch.univariate.base.ARCHModelResult.std_resid

should have .var() approx 1.  It isn't a big deal if they are close but not exact. The forecasts won't behave strangely if it is a little off.

What TMW says is wrong. If the variance is 1+delta then the only impact of delta is to change the long-run level of the forecast over very large horizons.  Over modest horizons (say 10 days) it should be virtually undetectable.

**Comment by rskene** [comment]
Yes, ok, they say something similar later on in the tutorial actually (though on a different issue).

So if we get >>>10 days then you would expect volatility to become unstable?

**Comment by bashtage** [comment]
No.  It will always be stable.  It just won't mean revert to the unconditional variance over very long horizons

**Comment by rskene** [comment]
Ok ... but what if the distribution you fit to the standardized residuals does not have Var=1?

So someone could make the case that the Weibull (just to pick something continuous with heavy tails)  is a better fit to the standardized residuals of the S&P (below).

And it has a variance of alot more than 1. And if we use Weibulll to generate random disturbances for the GARCH via `rng` parameter it becomes unstable immediately.

So, I guess if that's the case you aren't using GARCH anymore? Or maybe Mathworks is transforming the provided disturbances so that they have Var=1?

```
import arch
from arch.data.sp500 import load
import scipy.stats as scist

sp500 = 100 * load()["Adj Close"].pct_change().dropna()
mod = arch.arch_model(sp500, p=1, q=1)
res = mod.fit(update_freq=0, disp='off')

resid_params = scist.norm.fit(res.std_resid)
print (resid_params)
```
(-0.04379080259630351, 0.9991495479913962)

```
norm_ks = scist.kstest(res.std_resid, "norm", resid_params)
norm_ad = scist.anderson_ksamp((res.std_resid, scist.norm(*resid_params).rvs(size=res.std_resid.shape[0])))

wb_params = scist.weibull_min.fit(res.std_resid)
wb_ks = scist.kstest(res.std_resid, "weibull_min", wb_params)
wb_ad = scist.anderson_ksamp((res.std_resid, scist.weibull_min(*wb_params).rvs(size=res.std_resid.shape[0])))

norm_ks, wb_ks
```
(KstestResult(statistic=0.05040350219407097, pvalue=1.517517184828997e-11),
 KstestResult(statistic=0.8040058274456096, pvalue=0.0))
```
norm_ad, wb_ad
```
(Anderson_ksampResult(statistic=7.121594031843843, critical_values=array([0.325, 1.226, 1.961, 2.718, 3.752, 4.592, 6.546]), significance_level=0.001),
 Anderson_ksampResult(statistic=3271.067531146665, critical_values=array([0.325, 1.226, 1.961, 2.718, 3.752, 4.592, 6.546]), significance_level=0.001))

```
def custom_rng(params):
    def _rng(size):
        shocks = scist.weibull_min.rvs(*params, size=size) 
        return shocks
    return _rng

sims = res.forecast(start=sp500.index[-1], horizon=10, simulations=1, rng=custom_rng(cauchy_params), method='simulation')
sims.variance
```
```
 h.01 | h.02 | h.03 | h.04 | h.05 | h.06 | h.07 | h.08 | h.09 | h.10
 --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- 
3.59647 | 3.966258e+101 | 3.624951e+101 | 3.313014e+101 | 3.027920e+101 | 6.892402e+184 | 6.299291e+184 | 7.049241e+240 | 6.442634e+240 | 5.888761e+240
```

**Comment by bashtage** [comment]
> Ok ... but what if the distribution you fit to the standardized residuals does not have Var=1?

This is just a normalization.  Any RV that has a finite variance can be used to construct a distribution with variance 1 since if Var[Y] = s^2, then Var[X]=Var[Y/s] = 1.  Usually s depends on model parameters, e.g., a Student's t where s^2 = nu/(nu-2). 

You should always work with normalized distributions.  If you don't the intercept will adjust but you may get strange results.

> So someone could make the case that the Weibull (just to pick something continuous with heavy tails) is a better fit to the standardized residuals of the S&P (below).

The Weibull has bounded support so seems like a pretty poor distribution for returns.  It can be useful for modeling tails though, since you are only interested in values beyond some threshold.

> And it has a variance of alot more than 1. And if we use Weibulll to generate random disturbances for the GARCH via rng parameter it becomes unstable immediately.

You transform it to have unit variance.

> And if we use Weibulll to generate random disturbances for the GARCH via rng parameter it becomes unstable immediately.

What do you mean by unstable?  Is the simulated (average) path unstable?

**Comment by bashtage** [comment]
@rskene Is this resolved?

**Comment by rskene** [comment]
Yes, thanks for reminder. Found the second moment for my distribution, standardized the innovations. Works perfectly. thank you!
