### ISSUE TITLE
DOC: Parameter of SkewStudent distribution: nu or eta ?

### ISSUE THREAD

**Issue by kduxin** [bashtage/arch#511]
Hi! I am computing log-likelihood of the SkewStudent distribution. Here are a minimum example of mine.
```
from arch.univariate import ZeroMean, GARCH, SkewStudent
model = ZeroMean(x)
model.volatility = GARCH(1,1)
model.distribution = SkewStudent()

fit = model.fit()
print(fit.params)
```
The printed params contains two: `nu` and `lambda`.
However, the SkewStudent.loglikelihood() requires two params: `eta` and `lambda`.
I guess `nu` is the degree of freedom in a Student's t distribution. But is `eta` an alias to `nu` ?

**Comment by bashtage** [comment]
They are the same. I need to fix them to match. Will probably keep nu since it is the same as in the standardized t.
