### ISSUE TITLE
Forecasting with exogenous variables and no lags

### ISSUE THREAD

**Issue by lfdmotta** [bashtage/arch#513]
If one runs the documentation example of forecasting with external regressors **but sets the number of lags to zero** in the mean AR(m) model, 

```
mod = arch_model(y, x=exog, mean="ARX", lags=0)
```

one will get an error at this point:

```
x = {"x0": x0_oos[-1], "x1": x1_oos[-1]}
sim_fixedx = res.forecast(horizon=10, x=x, method="simulation", simulations=100)
```

The error message is:

> Traceback (most recent call last):
>   File "...\venv\lib\site-packages\IPython\core\interactiveshell.py", line 3437, in run_code
>     exec(code_obj, self.user_global_ns, self.user_ns)
>   File "<ipython-input-7-281ff61227a7>", line 2, in <module>
>     sim_fixedx = res.forecast(horizon=10, x=x, method="simulation", simulations=100)
>   File "...\venv\lib\site-packages\arch\univariate\base.py", line 1516, in forecast
>     x=x,
>   File "...\venv\lib\site-packages\arch\univariate\mean.py", line 989, in forecast
>     + shocks[path_loc, :, j]
> ValueError: shapes (100,0) and (2,) not aligned: 0 (dim 1) != 2 (dim 0)

This will be the case for numpy 1.21.0 and python 3.7. 

I came across this issue trying to use `forecast(method="simulation")` with zero lags and I thus far have not been able to make it work. I get the exact same error in my own codes. It boils down to some issue with this line:

```
+ mean_paths[path_loc, :, j : m + j].dot(dynp_rev)
```

in the mean.py code. The ``mean_paths`` is always coming as an empty array and the dot product raises the ValueError.

**Comment by bashtage** [comment]
What code are you referring to?  The notebook runs as expected with NumPy 1.21.  Can you post a complete example that reproduces the error you are seeing?

**Comment by lfdmotta** [comment]
The documentation example with ``lags=0`` will run into this error:

https://arch.readthedocs.io/en/latest/univariate/univariate_forecasting_with_exogenous_variables.html

**Comment by bashtage** [comment]
Seems to work for me:

https://gist.github.com/bashtage/cc9075266584b183a7519f6697a3bb34

**Comment by bashtage** [comment]
Can you do the same on your system and post a screen shot of the exception?

**Comment by lfdmotta** [comment]
```
from arch.univariate import ARX, GARCH, ZeroMean, arch_model
import numpy as np
import pandas as pd

burn = 250

x_mod = ARX(None, lags=1)
x0 = x_mod.simulate([1, 0.8, 1], nobs=1000 + burn).data
x1 = x_mod.simulate([2.5, 0.5, 1], nobs=1000 + burn).data

resid_mod = ZeroMean(volatility=GARCH())
resids = resid_mod.simulate([0.1, 0.1, 0.8], nobs=1000 + burn).data

phi1 = 0.7
phi0 = 3
y = 10 + resids.copy()
for i in range(1, y.shape[0]):
    y[i] = phi0 + phi1 * y[i - 1] + 2 * x0[i] - 2 * x1[i] + resids[i]

x0 = x0.iloc[-1000:]
x1 = x1.iloc[-1000:]
y = y.iloc[-1000:]
y.index = x0.index = x1.index = np.arange(1000)

# forecasting
x0_oos = np.empty((1000, 10))
x1_oos = np.empty((1000, 10))
for i in range(10):
    if i == 0:
        last = x0
    else:
        last = x0_oos[:, i - 1]
    x0_oos[:, i] = 1 + 0.8 * last
    if i == 0:
        last = x1
    else:
        last = x1_oos[:, i - 1]
    x1_oos[:, i] = 2.5 + 0.5 * last

x1_oos[-1]

# fit
exog = pd.DataFrame({"x0": x0, "x1": x1})
mod = arch_model(y, x=exog, mean="ARX", lags=0)
res = mod.fit(disp="off")
print(res.summary())


# forecast
exog_fcast = {"x0": x0_oos[-1:], "x1": x1_oos[-1:]}
forecasts = res.forecast(horizon=10, x=exog_fcast, method='simulation', simulations=100)
```

**Comment by bashtage** [comment]
Thanks - found the bug, and fixed in master now.
