### ISSUE TITLE
Buffer error - recursions.pyx in arch.univariate.recursions.garch_recursion()

### ISSUE THREAD

**Issue by karunakar2** [bashtage/arch#529]
Hi there,

thanks for the package.
The following error seems to be due to change in the arguments, need an update.
users\karunakar.kintada\appdata\local\programs\python\python39\lib\site-packages\arch\univariate\base.py in fit(self, update_freq, disp, starting_values, cov_type, show_warning, first_obs, last_obs, tol, options, backcast)
    655         self._backcast = backcast
--> 656         sv_volatility = v.starting_values(resids)
    657         self._var_bounds = var_bounds = v.variance_bounds(resids)

users\karunakar.kintada\appdata\local\programs\python\python39\lib\site-packages\arch\univariate\volatility.py in starting_values(self, resids)
   2005         llfs = alphas.copy()
-> 2006         var_bounds = self.variance_bounds(resids)
   2007         for i, alpha in enumerate(alphas):

users\karunakar.kintada\appdata\local\programs\python\python39\lib\site-packages\arch\univariate\volatility.py in variance_bounds(self, resids, power)
   1023     def variance_bounds(self, resids: Float64Array, power: float = 2.0) -> Float64Array:
-> 1024         return super().variance_bounds(resids, self.power)
   1025 

users\karunakar.kintada\appdata\local\programs\python\python39\lib\site-packages\arch\univariate\volatility.py in variance_bounds(self, resids, power)
    523         initial_value = w.dot(resids[:tau] ** 2.0)
--> 524         ewma_recursion(0.94, resids, var_bound, resids.shape[0], initial_value)
    525 

users\karunakar.kintada\appdata\local\programs\python\python39\lib\site-packages\arch\univariate\volatility.py in ewma_recursion(lam, resids, sigma2, nobs, backcast)
    133     var_bounds = np.ones((nobs, 2)) * np.array([-1.0, 1.7e308])
--> 134     rec.garch_recursion(
    135         np.array([0.0, 1.0 - lam, lam]),

arch\univariate\recursions.pyx in arch.univariate.recursions.garch_recursion()

ValueError: Buffer has wrong number of dimensions (expected 1, got 2)

**Comment by bashtage** [comment]
Can you post a complete example that shows how this is created?

**Comment by bashtage** [comment]
I'm going to close as I can't reproduce. I suspect something isn't correct in your local machine.  If you still have problems and can post a reproducer, please put it below and I'll take a look.
