### ISSUE TITLE
I wonder whether quasi-maximum likelihood method is available?

### ISSUE THREAD

**Issue by danielyang1009** [bashtage/arch#539]
from my understanding, quasi-MLE vs normal-MLE is to adjust standard error when doing test statistics, I wonder whether quasi-maximum likelihood method is available?

**Comment by bashtage** [comment]
When calling fit, set `cov_type` to "classic" for MLE or "robust" for QMLE. QMLE is the default.

**Comment by danielyang1009** [comment]
thanks for clarification, and thanks for your great works!
