### ISSUE TITLE
phi parameter in FIGARCH model

### ISSUE THREAD

**Issue by alejandro-cermeno** [bashtage/arch#541]
Hello: 

What is and how is the phi parameter interpreted in the FIGARCH model equation? Is it correct that omega is the constant in the volatility equation and beta is the lagged conditional variance parameter?

FIGARCH equation:
![image](https://user-images.githubusercontent.com/77359430/145735594-aca37592-bd7c-4057-9577-f1e4aaf48d3c.png)

The ARCH package also calls phi to the lag parameter in the equation of the mean when this is AR. Could you suggest to me some alternative name?

Mean AR equation:
![image](https://user-images.githubusercontent.com/77359430/145735756-3bc978ee-4280-426e-a0f1-76c5f5b9666f.png)

Thanks for your work and for the answer

**Comment by bashtage** [comment]
First, the equations and phis two are unrelated.  They are just two equations that use phi. 

In the FIGARCH the phi measures the sensitivity to the long-memory component.  You should probably check the original FIGARCH paper for more details on the parameterization.

**Comment by bashtage** [comment]
Going to close since no action for the package. Please feel free to continue to post if further clarification is needed.
