### ISSUE TITLE
This is not an issue, but I want to know how the volatility itself is calculated from the time-series data given 

### ISSUE THREAD

**Issue by VolkaneicFox** [bashtage/arch#543]
Hi,

I recently found this package and I am trying to compare the results from my own optimization to the parameters generated by arch_model. I am doing this for bitcoin data on GARCH(1,1). 
I use a rolling std, annualised by sqrt(365) for 20 instance window. I cannot figure out how the arch_model package calculates the volatility. Can someone please help, I am (more than) a little confused.

**Comment by bashtage** [comment]
What command are you having problems with? Can you post your code. 

A basic arch model is similar to an exponentially weighted moving average, and is technically a combination of an EWMA and a non-zero constant.

**Comment by bashtage** [comment]
Going to close due to a lack of follow up.
