### ISSUE TITLE
ARCH with specified lags

### ISSUE THREAD

**Issue by fancunwei95** [bashtage/arch#555]
This is not an issue. I am just curious about whether it is possible to have an ARCH model that only have sparse lags. 
That is for example, if for an ARCH(3) model, I know the lag 2 and lag 1 coefficients are zero, can I fit a model like  
```
\sigma_t^2 = \alpha_0 + \alpha_3 a_{t-3}^2
```
in the `arch_model`? I see you can specify sparse lags for AR or MA mean models. But for the volatility process, I do not know how to do that. Thanks!

**Comment by bashtage** [comment]
This has been requested once before but has not been implemented.

**Comment by fancunwei95** [comment]
Thanks!
