### ISSUE TITLE
noarch or osx-arm64 conda build?

### ISSUE THREAD

**Issue by ahgraber** [bashtage/arch#564]
Is it possible to build for `noarch` or `osx-arm64` platform on conda?

Thanks!

**Comment by bashtage** [comment]
Can't make a noarch one since it has a binary component. 

There are PyPi osx arm64 here: https://pypi.org/project/arch/#files

I'll see if it is possible to build the latest release using conda-forge for osx-arm64.

**Comment by bashtage** [comment]
Conda forge packages should be available shortly.
