### ISSUE TITLE
ImportError: cannot import name 'version' from 'arch._version' (C:\Users\

### ISSUE THREAD

**Issue by PeterWReed** [bashtage/arch#568]
I just download arch-py using - conda install -c conda-forge arch-py 

Running Jupyter notebook - The version of the notebook server is: 6.4.6. Python 3.8.12 (default, Oct 12 2021, 03:01:40) [MSC v.1916 64 bit (AMD64)].   OS is Windows 11 Pro.

The command(s) "import arch" and "from arch import arch_model" returns the error:
ImportError: cannot import name 'version' from 'arch._version' (C:\Users\<userName>\anaconda3\lib\site-packages\arch\_version.py)

The file "_version.py" is attached with file type changed for uploading:
[_version.py.txt](https://github.com/bashtage/arch/files/8394140/_version.py.txt)

**Comment by bashtage** [comment]
Thanks for reporting.  I made some changes to how versioning is done and the conda recipe needs some work.  You should be able to install from pip (`pip install arch`) or to pin to the previous using conda-forge (`conda install -c conda-forge "arch<5.2.0"`)

**Comment by bashtage** [comment]
Should be fixed shortly when conda-forge regenerated the build 5.2, build 2 packages.
