### ISSUE TITLE
Inquiring about Backward compatibility in arch

### ISSUE THREAD

**Issue by agarwl** [bashtage/arch#569]
Hi,

I maintain a [open-source project for evaluation of ML algorithms](https://github.com/google-research/rliable) which depends heavily on bootstrapping functionality in arch. It seems that there were some recent changes in arch and code only works for arch version `5.0.1`. Should I depend on a fixed version of arch (5.0.1) if changes in the future can possibly be backward incompatible?

PS: Thanks a lot for open-sourcing this great library. 

Regards,
Rishabh

**Comment by bashtage** [comment]
I try to avoid breaking changes except a cross majors. 5.0.1 was the first working release of the 5 series. Does your code not work with 5.1.0 or 5.2.0? You should be able to safely pin `arch>=5.0.1,<6`

**Comment by agarwl** [comment]
The code works with 5.0.1 but doesn't work with 5.2.0. I released the code when arch version was `4.17`.

**Comment by bashtage** [comment]
Can you provide an example of the issue where it breaks?  I'm surprised this happened.

**Comment by bashtage** [comment]
Here is the diff:

https://github.com/bashtage/arch/compare/v5.0.1...v5.2.0

There are not code changes to the bootstrapping code aside from some `assert` statements that are used with mypy typing.  Are you seeing assertion errors?

**Comment by bashtage** [comment]
https://github.com/bashtage/arch/compare/v5.0.1...v5.2.0#diff-3d824c14fc25d17aea27ed00d76b3bb2a1fdcabe3119d2d770872f72e8ab4429R1294

and

https://github.com/bashtage/arch/compare/v5.0.1...v5.2.0#diff-3d824c14fc25d17aea27ed00d76b3bb2a1fdcabe3119d2d770872f72e8ab4429R1300

Are the only two places where something could happen from what I can tell.  Are your indices something else?

**Comment by bashtage** [comment]
I am expecting `ndarray` when you are passing `tuple[ndarray,...]`. I think `tuple[ndarray,...]` can be acceptable, but will need to think about it.  The difference arises since you are implementing the bootstrap in 2 dimensions.

A short term solution would be to add the `_resample` method to your classes where you do not enforce the assert.

**Comment by agarwl** [comment]
Thanks for the quick response, will test it once the new version releases!
