### ISSUE TITLE
`power` parameter is FIGARCH appears to be ignored during fit

### ISSUE THREAD

**Issue by anthonybritto** [bashtage/arch#572]
Hi there,
Thanks for your excellent work with this package. I noticed some unexpected behaviour with the `FIGARCH` model that I thought I would report.

Here is the output of a (1, 1) model with `power=2` (yes, I know that this isn't a very good model).

![image](https://user-images.githubusercontent.com/52748631/165140007-f5aa45d7-6d48-4680-a513-8be2f1abb650.png)

Here's the output of the same model but with `power=1`:

![image](https://user-images.githubusercontent.com/52748631/165140174-ba5114ee-4b65-4723-8239-691cf34cddd0.png)

And for good measure, `power=0.5`:

![image](https://user-images.githubusercontent.com/52748631/165140294-cf8774c5-fc2c-4e4d-86f0-c0741c62be47.png)

As far as I can tell, the models are completely identical, leading me to believe that the `power` parameter is somehow being ignored.

Or am I missing something simple?

Thanks,
Anthony

**Comment by bashtage** [comment]
FIGARCH doesn't support `power`, which would make it FIAPARCH (which isn't implemented).  `power` is exclusively used with the `GARCH` process, which includes both symmetric and asymmetric models.

**Comment by anthonybritto** [comment]
@bashtage Thanks for the response. I was just going off the documentation, which does include a `power` parameter and an FIAVGARCH example: https://arch.readthedocs.io/en/latest/univariate/generated/arch.univariate.FIGARCH.html#arch.univariate.FIGARCH

So I take it then that the current implementation, using the notation in the documentation, has $d=2$ fixed? Thanks.

**Comment by bashtage** [comment]
Maybe a bug. Will need to check.

**Comment by bashtage** [comment]
The issue is that `arch_model` doesn't pass `power` to `FIGARCH`. If you direlty use `FIGARCH` it works.

**Comment by bashtage** [comment]
Fixed in master. In the mean time you can directly specify the model directly without using

**Comment by anthonybritto** [comment]
@bashtage Great, thank you!
