### ISSUE TITLE
GARCH-M implementation

### ISSUE THREAD

**Issue by Alessiobrini** [bashtage/arch#576]
Is it possible to estimate (G)ARCH-M variants with this toolbox? I am an extensive `arch` package user, but maybe I am missing something from the documentation.

With some effort, one could maybe implement GARCH-M, but I am wondering if I could produce the same effect by simply:
- Estimate a GARCH-like model as those implemented in the toolbox,
-  Take the conditional volatility and regress it against the same return one uses to estimate the former. The resulting coefficient should resemble the GARCH-M effect.

If this holds, it should be stated in the documentation to help future users.

**Comment by bashtage** [comment]
It is available:  https://bashtage.github.io/arch/univariate/generated/arch.univariate.ARCHInMean.html#arch.univariate.ARCHInMean

**Comment by bashtage** [comment]
Great.
