### ISSUE TITLE
Installation of `arch==5.0.1` fails on MacBook Pro with M1 chip

### ISSUE THREAD

**Issue by qgallouedec** [bashtage/arch#581]
Hi,

`pip install arch==5.0.1` fails on my MacBook Pro with M1 chip.
I also try on older MacBook Pro (but same OS version), and on a Linux system, and the installation succeed. That's why I think it is mainly related with the chip.

| | MacBook Pro with M1 chip | MacBook Pro with Intel chip | Ubuntu 20.04 |
|-|-|-|-|
| arch==5.0.1 | ❌ | ✅ | ✅|
| arch==5.1.0 | ✅ | ? | ✅ |
| arch==5.2.0 | ✅ | ? | ✅ |

You can read full log here: https://github.com/google-research/rliable/issues/13#issuecomment-1162847655

## System information

- Python version: 3.9
- Pip version: 22.1.2
- System Version: macOS 12.4 (21F79)
- Kernel Version: Darwin 21.5.0

## Expectation

As you can see, this problem has been solved as of version 5.1.0. I'm opening this issue mainly to help us better understand where this error came from.

**Comment by bashtage** [comment]
5.0.1 fails because it is forcing you to build and old NumPy which doesn't support OSX/Arm.  5.3.0 is out now which should do the job.
