### ISSUE TITLE
Forecast method for ARCHModelResult class doesn't seem to work

### ISSUE THREAD

**Issue by petergzli** [bashtage/arch#60]
The forecast method doesn't seem to make sense. It returns an array of the same length as my input array of returns. It should forecast subsequent volatilities perhaps for a given n-steps ahead (which may require specifying as a parameter the number of steps ahead). 

Or am I not using it correct? 

I'm also confused as to what the forecast could be for, as the first few numbers don't seem to match the variance of volatility as the modelresult.conditional_volatilty call.

**Comment by bashtage** [comment]
@petergzli I added some further explanation - let me know if this isn't clear.

**Comment by petergzli** [comment]
@bashtage Thank you for the edits to the doc for the cond. vol and the forecast(). Just to clarify from your explanation: if my returned vector has length(n), then the value in the last position (n-1) will be the h+1 next forecasted value in the time series?
