### ISSUE TITLE
Why the sqrt(2/pi) factor in EGARCH?

### ISSUE THREAD

**Issue by mikessut** [bashtage/arch#620]
I'm not sure where to ask this question.  Apologies if this is the wrong forum.

I'm trying to understand why there is a sqrt(2 / pi) factor in the EGARCH model.  

I've been trying to dig through some references on EGARCH to understand it better.  The[ brief discussion on Wikipedia](https://en.wikipedia.org/wiki/Autoregressive_conditional_heteroskedasticity#EGARCH) doesn't show this factor nor is there a factor in this reference ["Conditional Heteroskedasticity in Asset Returns: A New Approach"](https://www.jstor.org/stable/2938260).

https://github.com/bashtage/arch/blob/6e3325635fc0fd4cb6b7c4a305f610fc9b80a265/arch/univariate/volatility.py#L2504

**Comment by mikessut** [comment]
Of course I find a pretty good answer almost immediately after posting!  

I think this answers it, correct?

https://quant.stackexchange.com/questions/63939/egarch1-1-mean

**Comment by bashtage** [comment]
That is the right reason. It makes the absolute value shock have mean 0.  The other shock is already mean 0.

**Comment by mikessut** [comment]
Thanks!
