### ISSUE TITLE
Issue with Pip install

### ISSUE THREAD

**Issue by hvu89** [bashtage/arch#624]
I am using Mac OSX Intel with Anaconda Python 3.9.6.
When i try to install with pip install arch, this is the error I get.

> (base) hvu@hvu22145 ~ % pip install arch
> WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)'))': /simple/arch/
> WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)'))': /simple/arch/
> WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)'))': /simple/arch/
> WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)'))': /simple/arch/
> WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)'))': /simple/arch/
> Could not fetch URL https://pypi.org/simple/arch/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/arch/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)'))) - skipping
> ERROR: Could not find a version that satisfies the requirement arch (from versions: none)
> ERROR: No matching distribution found for arch

I've also tried to install from github with the following errors.

> (base) hvu@hvu22145 ~ % pip install git+https://github.com/bashtage/arch.git
> Collecting git+https://github.com/bashtage/arch.git
>   Cloning https://github.com/bashtage/arch.git to /private/var/folders/cm/qms65s1n0dq95gbv0mk_mzhm0000gp/T/pip-req-build-1il9j6zg
>   Running command git clone --filter=blob:none --quiet https://github.com/bashtage/arch.git /private/var/folders/cm/qms65s1n0dq95gbv0mk_mzhm0000gp/T/pip-req-build-1il9j6zg
>   Resolved https://github.com/bashtage/arch.git to commit 274143eca08f644ff67df524f4f6a645eb005776
>   Installing build dependencies ... error
>   error: subprocess-exited-with-error
>   
>   × pip subprocess to install build dependencies did not run successfully.
>   │ exit code: 1
>   ╰─> [9 lines of output]
>       Ignoring numpy: markers 'python_version >= "3.11"' don't match your environment
>       WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)'))': /simple/setuptools/
>       WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)'))': /simple/setuptools/
>       WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)'))': /simple/setuptools/
>       WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)'))': /simple/setuptools/
>       WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)'))': /simple/setuptools/
>       Could not fetch URL https://pypi.org/simple/setuptools/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/setuptools/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)'))) - skipping
>       ERROR: Could not find a version that satisfies the requirement setuptools>=61 (from versions: none)
>       ERROR: No matching distribution found for setuptools>=61
>       [end of output]
>   
>   note: This error originates from a subprocess, and is likely not a problem with pip.
> error: subprocess-exited-with-error
> 
> × pip subprocess to install build dependencies did not run successfully.
> │ exit code: 1
> ╰─> See above for output.
> 
> note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by bashtage** [comment]
You are having problems connecting to PyPI.  If you want you can install all of the requirements directly, and then install from github using

```
python -m  pip install git+https://github.com/bashtage/arch.git --no-build-isolation
```

In terms of requirements, you should have

```
setuptools>=61
wheel
setuptools_scm[toml]>=7,<8
oldest-supported-numpy
Cython>=0.29.24
```

**Comment by bashtage** [comment]
Happy to answer more questions, but closing since it isn't really anything I can fix.

**Comment by hvu89** [comment]
For anyone with this issue, i was able to resolve it by running this.

pip install --user --trusted-host files.pythonhosted.org --trusted-host pypi.org --trusted-host pypi.python.org --upgrade pip  arch
