### ISSUE TITLE
fit() without parameter vs. warm start

### ISSUE THREAD

**Issue by KIC** [bashtage/arch#625]
I am wondering why this package is not following the sklearn API and provide the y data in the fit method but in the constructor. The reason I am wondering is whether I can re-use a previously fitted arch model for a new slice of data i.e. by using a rolling window for backtests. Re-using already fitted parameters usually provide a much better initial guess and increases performance aka warm start.

**Comment by bashtage** [comment]
This package uses a scipy/statsmodels/linearmodels-api like design.

**Comment by bashtage** [comment]
If you want a warm start, you can do something like:

```
from arch.data import sp500
r = 100 * sp500.load().iloc[:,-2].pct_change().dropna()
mod = arch.arch_model(r)

last = None
for i in range(5000, len(r)):
    res = mod.fit(starting_values=last, last_obs=i, disp="off")
    last = res.params
```
