### ISSUE TITLE
Cannot reconcile simulation.values against simulation.residual_variances

### ISSUE THREAD

**Issue by sameerlal** [bashtage/arch#626]
I am trying to understand -- when forecasting using GARCH, how do the simulated "values" compare to the "residual_variances". From a few experiments, I cannot get them to match.

To be clear, I'm looking at these two properties in the ARCHModelForecast object:

* simulations.values
* simulations.residual_variances

From my understanding of the [docs](https://arch.readthedocs.io/en/latest/univariate/forecasting.html), the volatility series is "simulated" via drawing shocks e_t ~ N(0, 1) many times.  So there are (by default) 1000 "volatility paths", which are then averaged out to be the expected volatility. Each of these paths also correspond to a sequence of values (corresponding to epsilon_t in the docs), which is just white noise times sqrt(current modeled volatility). 

However, when I try to compare the following two, I don't get the same answer.

**Calculation 1**
- Compute` .fit( .. ).forecast( 5 days ).simulations.residual_variances`  
- Take the mean of the last row (corresponding to the expected volatility of the 5th day volatility forecast)

**Calculation 2**
- Compute `.fit(..).forecast( 5 days ).simulations.values`
- This results in a giant dataframe whcih is of size (num simulations) x ( 5 days )
- Take the last row (corresponding to the 5th day simulated return)
- Square these and take the mean (corresponding to E[ epsilon^2 ] [as written in the docs](https://arch.readthedocs.io/en/latest/univariate/forecasting.html)

These two don't always give the same result.  Any ideas why? I can provide more detail if anything is unclear.  Have gone through source code too, but no luck

**Comment by bashtage** [comment]
`simulations. Values` - These are simulated return.
`simulations.residual_variances`- These are the simulated variances

These should not give the exact same values.  The values have the mean in them if any.  Even if the mean is 0, squaring and averaging will only give you a noisy estimate of the final residual variance.

**Comment by bashtage** [comment]
Closing as answered
