### ISSUE TITLE
[DOC] Links to example notebooks for unit root tests and cointegration testing analysis

### ISSUE THREAD

**Issue by Vasudeva-bit** [bashtage/arch#689]
In `README.md`, links to [unit root testing example notebook](https://nbviewer.ipython.org/github/bashtage/arch/blob/main/examples/unitroot_examples.ipynb) and [cointegration testing example notebook](https://nbviewer.ipython.org/github/bashtage/arch/blob/main/examples/unitroot_cointegration_examples.ipynb) are broken.

**Comment by bashtage** [comment]
Thanks.  The URL changed.  Fixed now.
