### ISSUE TITLE
Are we using two-step approach for estimation?

### ISSUE THREAD

**Issue by barryyuberkeley** [bashtage/arch#696]
I may be wrong but it seems that the package is estimating the full model in two steps
1. estimate mean model parameters (zero mean / constant mean / AR / etc..) output residuals
2. estimate vol model parameters using the set of residuals in 1

I saw from the the summary that the degree of freedom is only nobs minus mean model parameters

If I am correct above, is there anyway to do a full MLE by finding the set of (mean parameters, vol parameters) simultaneously? It seems to be the other python package on garch is doing

Thanks very much!

**Comment by bashtage** [comment]
The estimation is all in one pass - full MLE of all parameters including mean, variance and distribution shapre.

**Comment by bashtage** [comment]
Going to close as answered. Please feel free to continue to post if there this isn't clear enough.
