### ISSUE TITLE
Threshold ARCH (TARCH)

### ISSUE THREAD

**Issue by jonathanng** [bashtage/arch#70]
Great job with the package!

According to this [paper](http://faculty.chicagobooth.edu/bryan.kelly/research/pdf/volfor.pdf), the TARCH model outperforms other models.

Would be great if this was added to the library.

**Comment by bashtage** [comment]
This model can be estimated using `GARCH` which handles a range of closely related models.

See  http://arch.readthedocs.org/en/latest/univariate/univariate_volatility_modeling.html?highlight=tarch#tarch-zarch and http://arch.readthedocs.org/en/latest/univariate/volatility.html#garch
