### ISSUE TITLE
How to modify GARCH model to incorporate new terms ?

### ISSUE THREAD

**Issue by a412h** [bashtage/arch#709]
I have read the documentation, but I cannot find a way to implement the following modification to the GJR GARCH model:
$\sigma_t^2 = \omega + \beta \sigma_{t-1}^2 + \gamma \epsilon_{t-1}^2 I_{ [ \epsilon_{t-1} < 0] } + \eta \epsilon_{t-1}^2I_{ [ \epsilon_{t-1} > 0] } .$
How do I implement the model above ?

**Comment by bashtage** [comment]
The model you have is observationally equivalent to a standard GJR_GARCH.

$\sigma_t^2 = \omega + \beta \sigma_{t-1}^2 + \gamma_1 \epsilon_{t-1}^2 I_{ [ \epsilon_{t-1} < 0] } + \eta \epsilon_{t-1}^2I_{ [ \epsilon_{t-1} > 0] } .$

is the same as 

$\sigma_t^2 = \omega + \beta \sigma_{t-1}^2 + \gamma_2 \epsilon_{t-1}^2 I_{ [ \epsilon_{t-1} < 0] } + \alpha \epsilon_{t-1}^2 .$  

where $\eta=\alpha$ and $\gamma_2 + \alpha = \gamma_1$.
