### ISSUE TITLE
Setting params 

### ISSUE THREAD

**Issue by jonathanng** [bashtage/arch#74]
I'm trying to manually input params like below:

        model = arch_model(returns)

        if params is None:
            res = model.fit(
                update_freq     = 0,
                disp            = 'off',
                starting_values = starting_values
            )
        else:
            res = arch.univariate.base.ARCHModelResult(
                params = params,
                model  = model
            )

        cvols = res.conditional_volatility

I'm getting an error. Looking through the code base, it appears I shouldn't be creating instances of ARCHModelResult. How do I create a time series of cvols given a returns series AND a set of parameters?

Thanks for your help!

**Comment by bashtage** [comment]
Are you trying to see the fit vols using a different set of parameters than those that were produced by fitting the model?  This might need some modification to be user friendly.

**Comment by jonathanng** [comment]
Yes, that's correct.

Why might I do this?

Let's say I fit the model get a model. I do this several times for the next several days. Finally, on the 8th day, I fit the model, and my parameter estimates are very different. Rather than using this new model, I'd feel more comfortable using yesterday's model, but with the most recent data (including the 8th day).

**Comment by bashtage** [comment]
I can see the use case - at a minimum it would simplify some comparisons across different sets of parameters.
