### ISSUE TITLE
fit function error

### ISSUE THREAD

**Issue by heyanyun** [bashtage/arch#75]
disp : str
            Either 'final' to print optimization result or 'off' to display
            nothing
but this
In [28]: res = am.fit(disp='off')
  NIT    FC           OBJFUN            GNORM
    1     6     8.482064E+03     2.081112E+03
    2    16     8.479741E+03     2.051243E+03
    3    25     8.478820E+03     1.043445E+03
    4    32     8.473472E+03     5.961454E+02
    5    39     8.472942E+03     7.603645E+02
    6    46     8.471053E+03     4.133681E+02
    7    53     8.470969E+03     5.918941E+02
    8    60     8.470657E+03     3.439708E+02
    9    66     8.470560E+03     1.033851E+02
   10    72     8.470536E+03     7.246581E+00
   11    78     8.470535E+03     8.108463E-01

**Comment by bashtage** [comment]
What version of SciPy are you using?

**Comment by bashtage** [comment]
I think this is fixed in master.
