### ISSUE TITLE
Valid starting values

### ISSUE THREAD

**Issue by jonathanng** [bashtage/arch#85]
I'm using a tarch model:

        model   = arch.arch_model(returns, p=1, o=1, q=1, power=1.0)

I'm having problems with convergence. So I thought entering the following starting value would make sense:

        starting_values = pd.Series(data={
            'mu':       0.0,
            'alpha[1]': 0.0,
            'gamma[1]': 0.0,
            'omega':    0.0,
            'beta[1]':  1.0
        })

Unfortunately, I'm getting the following warning:

> Starting values do not satisfy the parameter constraints in the model.  The provided starting values will be ignored.

**Comment by bashtage** [comment]
I believe omega > 0.  These are not good starting values since alpha=gamma=0 implies no dynamics.

**Comment by jonathanng** [comment]
I added some break points to figure out why, and I found that beta[1] was also an issue.

**Comment by bashtage** [comment]
Yes, alpha+0.5gamma+beta<1
