### ISSUE TITLE
coefficients of GARCH do not match R's values.  

### ISSUE THREAD

**Issue by mrajancsr** [bashtage/arch#86]
Hello, thanks for your update.  I have another issue.  Upon using your model, i cross checked the coefficients with R's built in function garchFit from the fGarch library;  Some of the coefficients are different starting from the 3rd significant digit.  example...

using intel's stock returns from "Analysis of financial time series" by Tsay, 
mu      omega     alpha1     alpha2     alpha3 
0.01256687 0.01042129 0.23288895 0.07506869 0.05199350 

These are the coefficients I got by calling  m1=garchFit(~1+garch(3,0),data=y,trace=F)
where y is the time series of the monthly returns.  

However, using your arch function, I get these coefficients:

mu          0.012529
omega       0.010503
alpha[1]    0.220955
alpha[2]    0.077879
alpha[3]    0.051980

This may not be a big issue.  I am not too sure.  But, different conclusions are reached based on the R's function and based on your library.  For instance, R showed that using an GARCH(3,0) model yields insignificant coefficients on the 2nd and 3rd alpha.  Whereas, using your model, it claims insignificant coefficients on the alpha 1,2 and 3.  Hence, which is correct?  I feel the issue has more to do with the coefficient values and the way the variance was initialized.  Please correct me if I am wrong.

**Comment by bashtage** [comment]
Which produces a higher log-likelihood?*  I have no knowledge of garchFIT's internals, how it initializes the variance, how it treats initial values, etc.  These all make differences.  Alternatively, you could plot the fit conditional variances -- I suspect that are visually indistinguishable.  

There is not such thing as a benchmark reference for ARCH-type models, and there are lots of choices about initial values that can make small differences.  Asymptotically these are all negligible, so they don't get studied.

* This is only meaningful if they use they both evaluate on the same data points - my packages uses all including the first 3.

**Comment by mrajancsr** [comment]
I compared your library to matlabs implementation and R's implementation.  The problem is, sometimes, under your library, the coefficients match pretty well.  Othertimes, it doesn't based on the type of distribution (for one particular data, your library matches), but for other data, your library gives negative log likelihood for the fitted model.  I recently downloaded crude oil data from bloomberg to undertake volatility modeling.  Its funny because when I specify the distribution to skewedStudent using GARCH(1,1), the log likelihoods match in your library and in R's implementation.  But, when I change it to studentT, your model produces -36750.60008 where as R and matlab produces a log likelihood of 10553.  Othertimes, an ARCH(10) model was used with Gaussian innovations that produced a log likelihood of -35555555 in your model but in R, i got a log likelihood of positive 3050.  

I don't know if this is a big issue at hand.  But since you are the volatility expert, I will give you the benefit of the doubt and just use your library.  Thanks

**Comment by bashtage** [comment]
If you fit the same GARCH model with different distributions, you should find that the LL of Normal <= LL or Stud T <= LL of Skew T.  In practice the difference in the LLs should be relatively small, usually less than a few hundred points.

Some implementation  (not mine) no not include constants that aren't important for optimization, but are important when comparing across distributions.

**Comment by mrajancsr** [comment]
Hello Dear Professor, Unfortunately, using your model, the LL of normal is > than LL of STu T in some cases.  attached is my implementation using your library.  Also, i included at the bottom the comparison with R's output.  You can see that R clearly outputs the conditional volatility.  Whereas using your library, it blows up.  

http://nbviewer.ipython.org/gist/mrajancsr/de08442e41645d66a683

**Comment by bashtage** [comment]
I don't have the exact same data, but I used WTI from FRED here and can't produce any issues (see bottom):

http://nbviewer.ipython.org/github/bashtage/arch/blob/check-convergence/examples/univariate_volatility_modeling.ipynb

Perhaps you need to scale the returns (I use 100 in the nb)?

**Comment by mrajancsr** [comment]
Hello Professor, 
yes you are right.  Scaling by 100 caused the program to work properly.  All the log likelihoods are negative and LL of normal is < the rest.  Going forward, is this a requirement in your program?  to scale by 100?

**Comment by bashtage** [comment]
It is generally a good idea to scale returns so that omega has a similar
order of magnitude to alpha or beta.  Ultimately this causes a problem for
the optimizer fmin_slsqp which isn't under my control.

I think you were seeing false convergence or other numerical problems
triggered by a small unconditional variance.

**Comment by bashtage** [comment]
I'm going to close this.  Should add to documentation about return scaling.

**Comment by crazyhyz** [comment]
I have the same question here. Basically, ARCH's result and R's result don't match. I don't know which one to believe.

**Comment by bashtage** [comment]
Can you provide some details about the data and the estimates?
