### ISSUE TITLE
Non-zero exit code for fmin_slsqp

### ISSUE THREAD

**Issue by avneeshs1** [bashtage/arch#87]
I am running into situations (mainly because of scaling issues of data) that are causing the scipy's optimizer to fail with errors like "Inequality constraints incompatible    (Exit mode 4)". Currently, there is no way to know if the optimization succeeded or not as the code does not check the exit status. Would it be possible to either raise an exception if the exit_code from fmin_slsqp is non-zero? I am worried that if I run GARCH on a whole bunch of time-series, opt would fail at places without me noticing.

Thanks

**Comment by bashtage** [comment]
Good idea - should definitely provide this information.

**Comment by bashtage** [comment]
Do you have a sharable dataset that does not converge?  I am having a hard time creating one by simulation.  

Kevin

**Comment by avneeshs1** [comment]
This seems to do the trick. arch.arch_model(numpy.array([1e-6,1.2e-6,1.4e-6,1.55e-6]*10)).fit()
