### ISSUE TITLE
Enhancement request: calculate conditional volatility using data from the last period

### ISSUE THREAD

**Issue by avneeshs1** [bashtage/arch#89]
Currently, GARCHModelResult.conditional_volatility does not include results for the t+1period (t being the last time-period in the data). In other words, there is no way to get conditional vol which uses information from the last time period. Not sure if the .forecast method was designed for this purpose but that is not implemented currently. 

My workaround was to basically re-implement recursion.garch_recursion by removing the 1 day lag. 

It would be great if this was natively supported.

**Comment by bashtage** [comment]
Another good idea - the difficult with a general purpose forecast is that for h > 1 the forecast is not necessarily analytic (i.e., for any volatility model that isn't linear in the squares, such as EGARCH).  However, the 1 step always is for any model, so this is a simple way to think about starting on the forecasting.

**Comment by bashtage** [comment]
#132 should provide this and more once merged.

**Comment by bashtage** [comment]
Fixed in #132
