### ISSUE TITLE
Logic reversed in EGARCH recursion bounds check

### ISSUE THREAD

**Issue by capellini** [bashtage/arch#91]
In the [bounds check for EGARCH recursion](https://github.com/bashtage/arch/blob/56ad1fb5a42f91df2606f54a55947882ce028176/arch/univariate/recursions.pyx#L272-L275), when the upper bound is exceeded, the logic appears to be inverted.  That is, if sigma2 exceeds DBL_MAX, we attempt to use it, rather than just using a constant.

The logic appears to be ok in the [pure python recursion](https://github.com/bashtage/arch/blob/56ad1fb5a42f91df2606f54a55947882ce028176/arch/univariate/recursions_python.py#L231-L234) file, because it checks for NOT inf before using sigma2.

I would submit a PR, but I want to figure out why my current PR is failing the build and get a better idea of the build process before doing that.

**Comment by bashtage** [comment]
Thanks for this.  You are welcome to submit a PR or I can easily fix.

**Comment by capellini** [comment]
Fixed in c1e41df
