### ISSUE TITLE
Potential bug in ARCHModel.fit()?

### ISSUE THREAD

**Issue by capellini** [bashtage/arch#94]
I was looking through some of the arch package code and noticed [this code snippet](https://github.com/bashtage/arch/blob/943a58892ba365f9026d3953897f43b3b4a3c2aa/arch/univariate/base.py#L441-L445) and was wondering why it works.  We initialize sigma2 to be a vector of zeros.  The next thing that we do with sigma is use it in the denominator in line 445.  Why doesn't this throw a divide by zero error?

Would it be safer to initialize it as a vector of ones, rather than zeros?  I just want to make sure that I'm not missing something.  If not, then I can make the change and submit the PR.

**Comment by bashtage** [comment]
Yes - I somehow removed the initialization of sigma2 in an earlier commit.
